---
- hosts: all


  vars:
    app_trunk: '{{domain["app_root"]|default("~")|expanduser}}/{{app_details["name"]}}'
    test_trunk: '../test_trash/{{app_details["name"]}}'
    #ansible_common_remote_group is needed for become_user: notroot to work
    ansible_common_remote_group: '{{domain["group"]}}'


  vars_files:
    - vars/vault.yml
    - vars/globals.yml
    - vars/os_paths.yml

  handlers:
    - name: Restart tomcat
      become: true
      service:
        name: 'tomcat'
        enabled: true
        daemon_reload: true
        state: restarted
        scope: user
      become: true
      become_user: '{{domain["server_user"]}}'
      environment:
        XDG_RUNTIME_DIR: "/run/user/{{ the_user_uid.stdout }}"


  pre_tasks:
    - name: Check that latest is pushed up.
      include_role:
        name: repo-check
      when: hostvars.localhost.skip_to_exit is not defined and inventory_hostname not in ["127.0.0.1", "localhost"]
    - name: End early?
      meta: end_play
      when: hostvars.localhost.skip_to_exit|default(omit) == true
    - include_vars: "{{ item }}"
      with_first_found:
        - 'vars/packages/vars_{{ansible_distribution}}{{ansible_distribution_major_version}}.yml'
    - include_vars: 
        file: 'vars/local_keys.yml'
        hash_behaviour: merge
      when: inventory_hostname in ["127.0.0.1", "localhost"]
    - name: Keys for local
      set_fact:
        ansible_user: '{{lookup("env", "USER")}}'
        domain: '{{ domain | combine(local_domain)}}'
      vars:
          local_domain:
            app_root: '{{"~"|expanduser}}'
            group: '{{ansible_env.USER}}'
            user: '{{ansible_env.USER}}'
            server_user: '{{ansible_env.USER}}'
            exports_dir: '/home/{{ansible_env.USER}}/keys'
            envs:
              web_app_key: '{{app_details["name"]}}_test'
      when: inventory_hostname in ["127.0.0.1", "localhost"]
    - name: Update apt cache if needed
      apt: update_cache=true cache_valid_time=604800
      become: true
      when: ansible_os_family == "Debian"
    - name: Install rsync
      become: true
      package:
        name: rsync
    - name: Install Chrony
      become: true
      package:
        name: '{{packages["chrony"]}}'
    - name: Ensure chrony is running.
      service:
        name: chronyd
        state: started
        enabled: true
    - name: Set local server settings
      set_fact:
        env_list:
        - name: "model" #api and client delivered from nginx
          port: 8033
          url: 'https://{{url_segments["base"]}}-model.{{url_segments["tld"]}}:8080'
          client_dir: '{{dev_dirs["web_root"]}}/{{app_details["name"]}}/client-model/'
          server_name: '{{url_segments["base"]}}-model.{{url_segments["tld"]}}'
          common_name: '{{url_segments["base"]}}-model.{{url_segments["tld"]}}'
          engine_dir: '{{app_trunk}}'
          ssh_dir: '{{dev_dirs["ssh"]|expanduser}}'
        - name: "rebug" #client delivered from nginx but api is from vs-code debugger
          port: 8032
          url: 'https://{{url_segments["base"]}}-rebug.{{url_segments["tld"]}}:8080'
          client_dir: '{{dev_dirs["web_root"]}}/{{app_details["name"]}}/client-rebug/'
          server_name: '{{url_segments["base"]}}-rebug.{{url_segments["tld"]}}'
          common_name: '{{url_segments["base"]}}-rebug.{{url_segments["tld"]}}'
          engine_dir: '{{app_trunk}}'
          ssh_dir: '{{dev_dirs["ssh"]|expanduser}}'
      when: inventory_hostname in ["127.0.0.1", "localhost"]
    - name: Set remote server settings
      set_fact:
        env_list:
          - name: "remote"
            port: 8033
            url: 'https://{{url_segments["base"]}}.{{url_segments["tld"]}}'
            client_dir: '{{dev_dirs["web_root"]}}/{{app_details["name"]}}/client/'
            server_name: '{{url_segments["base"]}}.{{url_segments["tld"]}}'
            common_name: ''
            engine_dir: '{{app_trunk}}'
            ssh_dir: ''
      when: ansible_host not in ["127.0.0.1", "localhost"] and not "192.168.0.0/16"|ansible.utils.network_in_usable(ansible_host)
    - name: Set VM server settings
      set_fact:
        env_list:
          - name: "vm"
            port: 8033
            url: 'https://{{url_segments["base"]}}-vm.{{url_segments["tld"]}}'
            client_dir: '{{dev_dirs["web_root"]}}/{{app_details["name"]}}/client/'
            server_name: '{{url_segments["base"]}}-vm.{{url_segments["tld"]}}'
            common_name: '{{url_segments["base"]}}-vm.{{url_segments["tld"]}}'
            engine_dir: '{{app_trunk}}'
            ssh_dir: ''
      when: ansible_host not in ["127.0.0.1", "localhost"] and "192.168.0.0/16"|ansible.utils.network_in_usable(ansible_host)
    - name: "Find uid of user"
      command: 'id -u {{domain["server_user"]}}'
      register: the_user_uid
      check_mode: no # Run even in check mode, otherwise the playbook fails with --check.
      changed_when: false
      become: true

  tasks:
    - name: setup java development on local
      include_role:
        name: java-setup
      vars:
        runat: localhost
        gradle_install: true
        java_user: '{{lookup("env", "USER")}}'
        java_group: '{{lookup("env", "USER")}}'
    - name: setup java development on remote
      include_role:
        name: java-setup
      vars:
        runat: '{{inventory_hostname}}'
        java_user: '{{domain["server_user"]}}'
        java_group: '{{domain["group"]}}'
      when: ansible_host not in ["127.0.0.1", "localhost"]
    - name: Build app 
      command:
        chdir: ../src
        argv:
          - './gradlew'
          - build
      register: jarred
      changed_when: '"executed" in jarred.stdout and "BUILD SUCCESSFUL" in jarred.stdout'
    - name: Copy set env
      copy:
        dest: '/home/{{domain["server_user"]}}/.sdkman/candidates/tomcat/current/bin/setenv.sh'
        content: |
          export DSF_APP_ROOT='{{app_trunk}}'
          export DSF_DB_PASS_API='{{keys["db_pass_api"]}}'
          export DSF_NAMESPACE_UUID='{{keys["namespace_uuid"]}}'
          export DSF_DATABASE_NAME='{{app_details["db"]}}'
          export DSF_AUTH_SECRET_KEY='{{keys["auth_secret_key"]}}'
          export DSF_BACK_KEY='{{keys["back_key"]}}'
          export DSF_CONTENT_DIR='{{app_trunk}}/content'
          export DSF_LIVE_CONFIG_PATH='{{app_trunk}}/app_conf.json'
          export DSF_EVENT_LOGS_DIR='{{app_trunk}}/event_logs'
          export DSF_VISIT_LOGS_DIR='{{app_trunk}}/visit_logs'
    - name: Copy war file
      copy:
        src: '../src/app/build/libs/app-plain.war'
        dest: '/home/{{domain["server_user"]}}/.sdkman/candidates/tomcat/current/webapps/space-habit-frontier-api.war'
      register: copied
      notify: Restart tomcat
    # - name: Replace API files
    #   become: true
    #   synchronize:
    #     src: ../src/api
    #     dest: '{{dev_dirs["web_root"]}}/{{app_details["name"]}}'
    #     delete: true
    # - name: Create directories
    #   file:
    #     path: '{{item}}'
    #     state: directory
    #     owner: '{{domain["server_user"]}}'
    #     group: '{{domain["group"]}}'
    #     mode: 'g+w'
    #   no_log: true
    #   become: true
    #   loop:
    #     - '{{app_trunk}}'
    #     - '{{domain["exports_dir"]}}'
    #     - '/home/{{domain["server_user"]}}/scripts'
    #     - '{{app_trunk}}/event_logs'
    #     - '{{app_trunk}}/visit_logs'
    # - name: Create directories for logged in user
    #   file:
    #     state: directory
    #     path: '{{item}}'
    #     owner: '{{ansible_user}}'
    #     group: '{{ansible_user}}'
    #   no_log: true
    #   become: true
    #   loop:
    #     - '/usr/local/share/{{app_details["name"]}}'
    #     - '/usr/local/share/{{app_details["name"]}}/migrations'
    # - name: Copy templates folder
    #   synchronize:
    #     src: '{{src_dirs["templates"]}}'
    #     dest: '{{app_trunk}}'
    #     delete: true
    # - name: Copy default app config
    #   copy:
    #     dest: '{{app_trunk}}/app_conf.json'
    #     src: app_conf.json
    #     owner: '{{domain["server_user"]}}'
    #     group: '{{domain["group"]}}'
    #     force: false
    #   become: true
    # - name: Python setup.
    #   include_role:
    #     name: python-setup
    #   vars:
    #     env_name: '{{app_details["prefix"]|lower}}_env'
    #     engine_src: '{{src_dirs["engine"]}}/'
    #     working_dir: '{{item["engine_dir"]}}'
    #     app_group: '{{domain["group"]}}'
    #   loop: '{{env_list}}'
    #   loop_control:
    #     label: '{{item.name}}'
    # - name: MySql setup
    #   include_role:
    #     name: mysql-setup
    #   vars:
    #     setup_pass: '{{keys["db_pass_setup"]}}'
    #     socket_path: '{{dev_files["mysql_socket"]}}'
    # - name: Copy alembic.ini
    #   copy:
    #     src: alembic.ini
    #     dest: '/usr/local/share/{{app_details["name"]}}/migrations/alembic.ini'
    #   when: inventory_hostname not in ["127.0.0.1", "localhost"]
    # - name: Replace alembic files
    #   synchronize:
    #     src: ../alembic
    #     dest: '/usr/local/share/{{app_details["name"]}}/migrations'
    #     delete: true
    #   become: true
    #   when: inventory_hostname not in ["127.0.0.1", "localhost"]
    # - name: Setup App Specific Db stuff.
    #   command:
    #     chdir: '/usr/local/share/{{app_details["name"]}}/migrations'
    #     argv:
    #       - '{{app_trunk}}/{{app_details["prefix"]|lower}}_env/bin/alembic'
    #       - upgrade
    #       - head
    #   register: migrate_results
    #   changed_when: '"Running upgrade" in migrate_results.stdout'
    #   environment:
    #     DSF_APP_ROOT: '{{app_trunk}}'
    #     DSF_DB_PASS_API: '{{keys["db_pass_api"]}}'
    #     DSF_DB_PASS_JANITOR: '{{keys["db_pass_janitor"]}}'
    #     DSF_DB_PASS_OWNER: '{{keys["db_pass_owner"]}}'
    #     DSF_DB_PASS_RADIO: '{{keys["db_pass_radio"]}}'
    #     DSF_DB_PASS_SETUP: '{{keys["db_pass_setup"]}}'
    #     DSF_DATABASE_NAME: '{{app_details["db"]}}'
    #     DSF_LIVE_CONFIG_PATH: '{{app_trunk}}/app_conf.json'
    # - name: Copy web app keys
    #   copy:
    #     dest: '{{domain["exports_dir"]}}/{{domain["envs"]["web_app_key"]}}'
    #     content: |
    #       AWS_ENDPOINT_URL='{{keys["aws_endpoint_url"]}}'
    #       AWS_ACCESS_KEY_ID='{{keys["aws_access_key_id"]}}'
    #       AWS_SECRET_ACCESS_KEY='{{keys["aws_secret_access_key"]}}'
    #       DSF_APP_ROOT='{{app_trunk}}'
    #       DSF_DB_PASS_API='{{keys["db_pass_api"]}}'
    #       DSF_DB_PASS_RADIO='{{keys["db_pass_radio"]}}'
    #       DSF_NAMESPACE_UUID='{{keys["namespace_uuid"]}}'
    #       DSF_TEMPLATES_DEST='{{app_trunk}}/files'
    #       DSF_ICES_CONFIGS_DIR='{{app_trunk}}/ices_configs'
    #       DSF_PY_MODULE_DIR='{{app_trunk}}/ices_modules'
    #       DSF_DATABASE_NAME='{{app_details["db"]}}'
    #       DSF_AUTH_SECRET_KEY='{{keys["auth_secret_key"]}}'
    #       DSF_BACK_KEY='{{keys["back_key"]}}'
    #       S3_BUCKET_NAME='{{keys["s3_bucket_name"]}}'
    #       S3_REGION_NAME='{{keys["s3_region_name"]}}'
    #       DSF_CONTENT_DIR='{{app_trunk}}/content'
    #       DSF_PYTHON_EXECUTABLE='{{app_trunk}}/{{app_details["prefix"]|lower}}_env/bin/python'
    #       DSF_ICES_EXECUTABLE='{{domain["app_root"]}}/.local/bin/{{app_details["prefix"]|lower}}-ices'
    #       DSF_LIVE_CONFIG_PATH='{{app_trunk}}/app_conf.json'
    #       DSF_EVENT_LOGS_DIR='{{app_trunk}}/event_logs'
    #       DSF_VISIT_LOGS_DIR='{{app_trunk}}/visit_logs'
    #       DSF_QUEUE_FILES_DIR='{{app_trunk}}/queues'
    #       DSF_SHUFFLED_ALPHABET='{{keys["shuffled_alphabet"]}}'
    #   # notify: Restart API #not sure this exists as a handler anymore
    # - name: Add API run script
    #   copy: 
    #     dest: '/home/{{domain["server_user"]}}/run_api.sh'
    #     content: |
    #       #!/bin/sh

    #       . {{app_trunk}}/{{app_details["prefix"]|lower}}_env/bin/activate &&
    #       uvicorn --app-dir \
    #       {{dev_dirs["web_root"]}}/{{app_details["name"]}}/api \
    #       --root-path /api/v1 \
    #       --host 0.0.0.0 \
    #       --port 8033 \
    #       index:app \
    #       </dev/null 
    #       #>api.out 2>&1
    #     owner: '{{domain["server_user"]}}'
    #     group: '{{domain["group"]}}'
    #     mode: 'u+x'
    #   become: true
    # - name: App API Service
    #   include_role:
    #     name: service-setup
    #   vars:
    #     service_name: run-api
    #     service_owner: '{{domain["server_user"]}}'
    #     service_group: '{{domain["group"]}}'
    #     service_description: Run the api
    #     env_file: '{{domain["exports_dir"]}}/{{domain["envs"]["web_app_key"]}}'
    #     service_command: '/home/{{domain["server_user"]}}/run_api.sh'
    # - name: Restart API
    #   service:
    #     name: run-api.service
    #     enabled: true
    #     state: restarted
    #     scope: user
    #   become: true
    #   become_user: '{{domain["server_user"]}}'
    #   environment:
    #     XDG_RUNTIME_DIR: "/run/user/{{ the_user_uid.stdout }}"
    # - name: Nginx setup
    #   include_role:
    #     name: nginx-setup
    #   vars:
    #     env_name: '{{item["name"]}}'
    #     server_name: '{{item["server_name"]}}'
    #     app_prefix: '{{app_details["name"]|to_snake()}}'
    #     api_port: '{{item["port"]}}'
    #     common_name: '{{item["common_name"]}}'
    #     ssh_dir: '{{item["ssh_dir"]}}'
    #     serve_dir: '{{item["client_dir"]}}'
    #   loop: '{{env_list}}'
    #   loop_control:
    #     label: '{{item.name}}'
    # - name: Client code setup
    #   include_role:
    #     name: client-setup
    #   vars:
    #     api_version: '{{app_details["api_version"]}}'
    #     full_url: '{{item["url"]}}'
    #     dest_dir: '{{item["client_dir"]}}'
    #   when: item.name != "debug"
    #   loop: '{{env_list}}'
    #   loop_control:
    #     label: '{{item.name}}'


