/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import space_habit_frontier.data_model.db_generated.tables.Actionevents;
import space_habit_frontier.data_model.db_generated.tables.Actions;
import space_habit_frontier.data_model.db_generated.tables.Adventureevents;
import space_habit_frontier.data_model.db_generated.tables.Dungeon;
import space_habit_frontier.data_model.db_generated.tables.FlywaySchemaHistory;
import space_habit_frontier.data_model.db_generated.tables.Hero;
import space_habit_frontier.data_model.db_generated.tables.Lkarmor;
import space_habit_frontier.data_model.db_generated.tables.Lkdungeonlkitems;
import space_habit_frontier.data_model.db_generated.tables.Lkdungeonlkmonsters;
import space_habit_frontier.data_model.db_generated.tables.Lkdungeons;
import space_habit_frontier.data_model.db_generated.tables.Lkitems;
import space_habit_frontier.data_model.db_generated.tables.Lkmonsters;
import space_habit_frontier.data_model.db_generated.tables.Lkusables;
import space_habit_frontier.data_model.db_generated.tables.Lkweapons;
import space_habit_frontier.data_model.db_generated.tables.Monsteritemdrops;
import space_habit_frontier.data_model.db_generated.tables.Todoevents;
import space_habit_frontier.data_model.db_generated.tables.Todos;
import space_habit_frontier.data_model.db_generated.tables.Users;
import space_habit_frontier.data_model.db_generated.tables.Usersessions;
import space_habit_frontier.data_model.db_generated.tables.Visitors;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.actionevents</code>.
     */
    public final Actionevents ACTIONEVENTS = Actionevents.ACTIONEVENTS;

    /**
     * The table <code>public.actions</code>.
     */
    public final Actions ACTIONS = Actions.ACTIONS;

    /**
     * The table <code>public.adventureevents</code>.
     */
    public final Adventureevents ADVENTUREEVENTS = Adventureevents.ADVENTUREEVENTS;

    /**
     * The table <code>public.dungeon</code>.
     */
    public final Dungeon DUNGEON = Dungeon.DUNGEON;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.hero</code>.
     */
    public final Hero HERO = Hero.HERO;

    /**
     * The table <code>public.lkarmor</code>.
     */
    public final Lkarmor LKARMOR = Lkarmor.LKARMOR;

    /**
     * The table <code>public.lkdungeonlkitems</code>.
     */
    public final Lkdungeonlkitems LKDUNGEONLKITEMS = Lkdungeonlkitems.LKDUNGEONLKITEMS;

    /**
     * The table <code>public.lkdungeonlkmonsters</code>.
     */
    public final Lkdungeonlkmonsters LKDUNGEONLKMONSTERS = Lkdungeonlkmonsters.LKDUNGEONLKMONSTERS;

    /**
     * The table <code>public.lkdungeons</code>.
     */
    public final Lkdungeons LKDUNGEONS = Lkdungeons.LKDUNGEONS;

    /**
     * The table <code>public.lkitems</code>.
     */
    public final Lkitems LKITEMS = Lkitems.LKITEMS;

    /**
     * The table <code>public.lkmonsters</code>.
     */
    public final Lkmonsters LKMONSTERS = Lkmonsters.LKMONSTERS;

    /**
     * The table <code>public.lkusables</code>.
     */
    public final Lkusables LKUSABLES = Lkusables.LKUSABLES;

    /**
     * The table <code>public.lkweapons</code>.
     */
    public final Lkweapons LKWEAPONS = Lkweapons.LKWEAPONS;

    /**
     * The table <code>public.monsteritemdrops</code>.
     */
    public final Monsteritemdrops MONSTERITEMDROPS = Monsteritemdrops.MONSTERITEMDROPS;

    /**
     * The table <code>public.todoevents</code>.
     */
    public final Todoevents TODOEVENTS = Todoevents.TODOEVENTS;

    /**
     * The table <code>public.todos</code>.
     */
    public final Todos TODOS = Todos.TODOS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * The table <code>public.usersessions</code>.
     */
    public final Usersessions USERSESSIONS = Usersessions.USERSESSIONS;

    /**
     * The table <code>public.visitors</code>.
     */
    public final Visitors VISITORS = Visitors.VISITORS;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Actionevents.ACTIONEVENTS,
            Actions.ACTIONS,
            Adventureevents.ADVENTUREEVENTS,
            Dungeon.DUNGEON,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            Hero.HERO,
            Lkarmor.LKARMOR,
            Lkdungeonlkitems.LKDUNGEONLKITEMS,
            Lkdungeonlkmonsters.LKDUNGEONLKMONSTERS,
            Lkdungeons.LKDUNGEONS,
            Lkitems.LKITEMS,
            Lkmonsters.LKMONSTERS,
            Lkusables.LKUSABLES,
            Lkweapons.LKWEAPONS,
            Monsteritemdrops.MONSTERITEMDROPS,
            Todoevents.TODOEVENTS,
            Todos.TODOS,
            Users.USERS,
            Usersessions.USERSESSIONS,
            Visitors.VISITORS
        );
    }
}
