/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated;


import space_habit_frontier.data_model.db_generated.tables.Actionevents;
import space_habit_frontier.data_model.db_generated.tables.Actions;
import space_habit_frontier.data_model.db_generated.tables.Adventureevents;
import space_habit_frontier.data_model.db_generated.tables.Dungeon;
import space_habit_frontier.data_model.db_generated.tables.FlywaySchemaHistory;
import space_habit_frontier.data_model.db_generated.tables.Hero;
import space_habit_frontier.data_model.db_generated.tables.Lkarmor;
import space_habit_frontier.data_model.db_generated.tables.Lkdungeonlkitems;
import space_habit_frontier.data_model.db_generated.tables.Lkdungeonlkmonsters;
import space_habit_frontier.data_model.db_generated.tables.Lkdungeons;
import space_habit_frontier.data_model.db_generated.tables.Lkitems;
import space_habit_frontier.data_model.db_generated.tables.Lkmonsters;
import space_habit_frontier.data_model.db_generated.tables.Lkusables;
import space_habit_frontier.data_model.db_generated.tables.Lkweapons;
import space_habit_frontier.data_model.db_generated.tables.Monsteritemdrops;
import space_habit_frontier.data_model.db_generated.tables.Todoevents;
import space_habit_frontier.data_model.db_generated.tables.Todos;
import space_habit_frontier.data_model.db_generated.tables.Users;
import space_habit_frontier.data_model.db_generated.tables.Usersessions;
import space_habit_frontier.data_model.db_generated.tables.Visitors;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.actionevents</code>.
     */
    public static final Actionevents ACTIONEVENTS = Actionevents.ACTIONEVENTS;

    /**
     * The table <code>public.actions</code>.
     */
    public static final Actions ACTIONS = Actions.ACTIONS;

    /**
     * The table <code>public.adventureevents</code>.
     */
    public static final Adventureevents ADVENTUREEVENTS = Adventureevents.ADVENTUREEVENTS;

    /**
     * The table <code>public.dungeon</code>.
     */
    public static final Dungeon DUNGEON = Dungeon.DUNGEON;

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.hero</code>.
     */
    public static final Hero HERO = Hero.HERO;

    /**
     * The table <code>public.lkarmor</code>.
     */
    public static final Lkarmor LKARMOR = Lkarmor.LKARMOR;

    /**
     * The table <code>public.lkdungeonlkitems</code>.
     */
    public static final Lkdungeonlkitems LKDUNGEONLKITEMS = Lkdungeonlkitems.LKDUNGEONLKITEMS;

    /**
     * The table <code>public.lkdungeonlkmonsters</code>.
     */
    public static final Lkdungeonlkmonsters LKDUNGEONLKMONSTERS = Lkdungeonlkmonsters.LKDUNGEONLKMONSTERS;

    /**
     * The table <code>public.lkdungeons</code>.
     */
    public static final Lkdungeons LKDUNGEONS = Lkdungeons.LKDUNGEONS;

    /**
     * The table <code>public.lkitems</code>.
     */
    public static final Lkitems LKITEMS = Lkitems.LKITEMS;

    /**
     * The table <code>public.lkmonsters</code>.
     */
    public static final Lkmonsters LKMONSTERS = Lkmonsters.LKMONSTERS;

    /**
     * The table <code>public.lkusables</code>.
     */
    public static final Lkusables LKUSABLES = Lkusables.LKUSABLES;

    /**
     * The table <code>public.lkweapons</code>.
     */
    public static final Lkweapons LKWEAPONS = Lkweapons.LKWEAPONS;

    /**
     * The table <code>public.monsteritemdrops</code>.
     */
    public static final Monsteritemdrops MONSTERITEMDROPS = Monsteritemdrops.MONSTERITEMDROPS;

    /**
     * The table <code>public.todoevents</code>.
     */
    public static final Todoevents TODOEVENTS = Todoevents.TODOEVENTS;

    /**
     * The table <code>public.todos</code>.
     */
    public static final Todos TODOS = Todos.TODOS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;

    /**
     * The table <code>public.usersessions</code>.
     */
    public static final Usersessions USERSESSIONS = Usersessions.USERSESSIONS;

    /**
     * The table <code>public.visitors</code>.
     */
    public static final Visitors VISITORS = Visitors.VISITORS;
}
