/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.engine.db_generated.Keys;
import space_habit_frontier.engine.db_generated.Public;
import space_habit_frontier.engine.db_generated.tables.Users.UsersPath;
import space_habit_frontier.engine.db_generated.tables.records.AdventureeventsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Adventureevents extends TableImpl<AdventureeventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.adventureevents</code>
     */
    public static final Adventureevents ADVENTUREEVENTS = new Adventureevents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AdventureeventsRecord> getRecordType() {
        return AdventureeventsRecord.class;
    }

    /**
     * The column <code>public.adventureevents.id</code>.
     */
    public final TableField<AdventureeventsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.adventureevents.eventtype</code>.
     */
    public final TableField<AdventureeventsRecord, Short> EVENTTYPE = createField(DSL.name("eventtype"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.adventureevents.creationtimestamp</code>.
     */
    public final TableField<AdventureeventsRecord, BigDecimal> CREATIONTIMESTAMP = createField(DSL.name("creationtimestamp"), SQLDataType.NUMERIC(16, 4).nullable(false), this, "");

    /**
     * The column <code>public.adventureevents.userid</code>.
     */
    public final TableField<AdventureeventsRecord, Long> USERID = createField(DSL.name("userid"), SQLDataType.BIGINT.nullable(false), this, "");

    private Adventureevents(Name alias, Table<AdventureeventsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Adventureevents(Name alias, Table<AdventureeventsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.adventureevents</code> table reference
     */
    public Adventureevents(String alias) {
        this(DSL.name(alias), ADVENTUREEVENTS);
    }

    /**
     * Create an aliased <code>public.adventureevents</code> table reference
     */
    public Adventureevents(Name alias) {
        this(alias, ADVENTUREEVENTS);
    }

    /**
     * Create a <code>public.adventureevents</code> table reference
     */
    public Adventureevents() {
        this(DSL.name("adventureevents"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<AdventureeventsRecord, Long> getIdentity() {
        return (Identity<AdventureeventsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AdventureeventsRecord> getPrimaryKey() {
        return Keys.ADVENTUREEVENTS_PKEY;
    }

    @Override
    public List<ForeignKey<AdventureeventsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ADVENTUREEVENTS__ADVENTUREEVENTS_USERID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.ADVENTUREEVENTS__ADVENTUREEVENTS_USERID_FKEY, null);

        return _users;
    }

    @Override
    public Adventureevents as(String alias) {
        return new Adventureevents(DSL.name(alias), this);
    }

    @Override
    public Adventureevents as(Name alias) {
        return new Adventureevents(alias, this);
    }

    @Override
    public Adventureevents as(Table<?> alias) {
        return new Adventureevents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Adventureevents rename(String name) {
        return new Adventureevents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Adventureevents rename(Name name) {
        return new Adventureevents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Adventureevents rename(Table<?> name) {
        return new Adventureevents(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Adventureevents where(Condition condition) {
        return new Adventureevents(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Adventureevents where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Adventureevents where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Adventureevents where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Adventureevents where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Adventureevents where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Adventureevents where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Adventureevents where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Adventureevents whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Adventureevents whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
