/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.engine.db_generated.Keys;
import space_habit_frontier.engine.db_generated.Public;
import space_habit_frontier.engine.db_generated.tables.Lkdungeons.LkdungeonsPath;
import space_habit_frontier.engine.db_generated.tables.Users.UsersPath;
import space_habit_frontier.engine.db_generated.tables.records.DungeonRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Dungeon extends TableImpl<DungeonRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.dungeon</code>
     */
    public static final Dungeon DUNGEON = new Dungeon();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DungeonRecord> getRecordType() {
        return DungeonRecord.class;
    }

    /**
     * The column <code>public.dungeon.id</code>.
     */
    public final TableField<DungeonRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.dungeon.title</code>.
     */
    public final TableField<DungeonRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<DungeonRecord, Object> COORDINATES = createField(DSL.name("coordinates"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"point\"").nullable(false), this, "");

    /**
     * The column <code>public.dungeon.lvl</code>.
     */
    public final TableField<DungeonRecord, Integer> LVL = createField(DSL.name("lvl"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.dungeon.lkdungeonid</code>.
     */
    public final TableField<DungeonRecord, Long> LKDUNGEONID = createField(DSL.name("lkdungeonid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.dungeon.userid</code>.
     */
    public final TableField<DungeonRecord, Long> USERID = createField(DSL.name("userid"), SQLDataType.BIGINT.nullable(false), this, "");

    private Dungeon(Name alias, Table<DungeonRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Dungeon(Name alias, Table<DungeonRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.dungeon</code> table reference
     */
    public Dungeon(String alias) {
        this(DSL.name(alias), DUNGEON);
    }

    /**
     * Create an aliased <code>public.dungeon</code> table reference
     */
    public Dungeon(Name alias) {
        this(alias, DUNGEON);
    }

    /**
     * Create a <code>public.dungeon</code> table reference
     */
    public Dungeon() {
        this(DSL.name("dungeon"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DungeonRecord, Long> getIdentity() {
        return (Identity<DungeonRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<DungeonRecord> getPrimaryKey() {
        return Keys.DUNGEON_PKEY;
    }

    @Override
    public List<ForeignKey<DungeonRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DUNGEON__DUNGEON_LKDUNGEONID_FKEY, Keys.DUNGEON__DUNGEON_USERID_FKEY);
    }

    private transient LkdungeonsPath _lkdungeons;

    /**
     * Get the implicit join path to the <code>public.lkdungeons</code> table.
     */
    public LkdungeonsPath lkdungeons() {
        if (_lkdungeons == null)
            _lkdungeons = new LkdungeonsPath(this, Keys.DUNGEON__DUNGEON_LKDUNGEONID_FKEY, null);

        return _lkdungeons;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.DUNGEON__DUNGEON_USERID_FKEY, null);

        return _users;
    }

    @Override
    public Dungeon as(String alias) {
        return new Dungeon(DSL.name(alias), this);
    }

    @Override
    public Dungeon as(Name alias) {
        return new Dungeon(alias, this);
    }

    @Override
    public Dungeon as(Table<?> alias) {
        return new Dungeon(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Dungeon rename(String name) {
        return new Dungeon(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dungeon rename(Name name) {
        return new Dungeon(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Dungeon rename(Table<?> name) {
        return new Dungeon(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dungeon where(Condition condition) {
        return new Dungeon(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dungeon where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dungeon where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dungeon where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dungeon where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dungeon where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dungeon where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Dungeon where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dungeon whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Dungeon whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
