/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.engine.db_generated.Keys;
import space_habit_frontier.engine.db_generated.Public;
import space_habit_frontier.engine.db_generated.tables.records.LkdungeonsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lkdungeons extends TableImpl<LkdungeonsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.lkdungeons</code>
     */
    public static final Lkdungeons LKDUNGEONS = new Lkdungeons();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LkdungeonsRecord> getRecordType() {
        return LkdungeonsRecord.class;
    }

    /**
     * The column <code>public.lkdungeons.id</code>.
     */
    public final TableField<LkdungeonsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.lkdungeons.title</code>.
     */
    public final TableField<LkdungeonsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.lkdungeons.exposition</code>.
     */
    public final TableField<LkdungeonsRecord, String> EXPOSITION = createField(DSL.name("exposition"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.lkdungeons.minlvl</code>.
     */
    public final TableField<LkdungeonsRecord, Short> MINLVL = createField(DSL.name("minlvl"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.lkdungeons.imageuri</code>.
     */
    public final TableField<LkdungeonsRecord, String> IMAGEURI = createField(DSL.name("imageuri"), SQLDataType.CLOB, this, "");

    private Lkdungeons(Name alias, Table<LkdungeonsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lkdungeons(Name alias, Table<LkdungeonsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.lkdungeons</code> table reference
     */
    public Lkdungeons(String alias) {
        this(DSL.name(alias), LKDUNGEONS);
    }

    /**
     * Create an aliased <code>public.lkdungeons</code> table reference
     */
    public Lkdungeons(Name alias) {
        this(alias, LKDUNGEONS);
    }

    /**
     * Create a <code>public.lkdungeons</code> table reference
     */
    public Lkdungeons() {
        this(DSL.name("lkdungeons"), null);
    }

    public <O extends Record> Lkdungeons(Table<O> path, ForeignKey<O, LkdungeonsRecord> childPath, InverseForeignKey<O, LkdungeonsRecord> parentPath) {
        super(path, childPath, parentPath, LKDUNGEONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LkdungeonsPath extends Lkdungeons implements Path<LkdungeonsRecord> {
        public <O extends Record> LkdungeonsPath(Table<O> path, ForeignKey<O, LkdungeonsRecord> childPath, InverseForeignKey<O, LkdungeonsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LkdungeonsPath(Name alias, Table<LkdungeonsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LkdungeonsPath as(String alias) {
            return new LkdungeonsPath(DSL.name(alias), this);
        }

        @Override
        public LkdungeonsPath as(Name alias) {
            return new LkdungeonsPath(alias, this);
        }

        @Override
        public LkdungeonsPath as(Table<?> alias) {
            return new LkdungeonsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<LkdungeonsRecord> getPrimaryKey() {
        return Keys.LKDUNGEONS_PKEY;
    }

    @Override
    public Lkdungeons as(String alias) {
        return new Lkdungeons(DSL.name(alias), this);
    }

    @Override
    public Lkdungeons as(Name alias) {
        return new Lkdungeons(alias, this);
    }

    @Override
    public Lkdungeons as(Table<?> alias) {
        return new Lkdungeons(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkdungeons rename(String name) {
        return new Lkdungeons(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkdungeons rename(Name name) {
        return new Lkdungeons(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkdungeons rename(Table<?> name) {
        return new Lkdungeons(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeons where(Condition condition) {
        return new Lkdungeons(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeons where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeons where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeons where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeons where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeons where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeons where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeons where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeons whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeons whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
