/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.engine.db_generated.Keys;
import space_habit_frontier.engine.db_generated.Public;
import space_habit_frontier.engine.db_generated.tables.Lkdungeons.LkdungeonsPath;
import space_habit_frontier.engine.db_generated.tables.Lkitems.LkitemsPath;
import space_habit_frontier.engine.db_generated.tables.records.LkdungeonlkitemsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lkdungeonlkitems extends TableImpl<LkdungeonlkitemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.lkdungeonlkitems</code>
     */
    public static final Lkdungeonlkitems LKDUNGEONLKITEMS = new Lkdungeonlkitems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LkdungeonlkitemsRecord> getRecordType() {
        return LkdungeonlkitemsRecord.class;
    }

    /**
     * The column <code>public.lkdungeonlkitems.lkdungeonid</code>.
     */
    public final TableField<LkdungeonlkitemsRecord, Long> LKDUNGEONID = createField(DSL.name("lkdungeonid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.lkdungeonlkitems.lkitemid</code>.
     */
    public final TableField<LkdungeonlkitemsRecord, Long> LKITEMID = createField(DSL.name("lkitemid"), SQLDataType.BIGINT.nullable(false), this, "");

    private Lkdungeonlkitems(Name alias, Table<LkdungeonlkitemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lkdungeonlkitems(Name alias, Table<LkdungeonlkitemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.lkdungeonlkitems</code> table reference
     */
    public Lkdungeonlkitems(String alias) {
        this(DSL.name(alias), LKDUNGEONLKITEMS);
    }

    /**
     * Create an aliased <code>public.lkdungeonlkitems</code> table reference
     */
    public Lkdungeonlkitems(Name alias) {
        this(alias, LKDUNGEONLKITEMS);
    }

    /**
     * Create a <code>public.lkdungeonlkitems</code> table reference
     */
    public Lkdungeonlkitems() {
        this(DSL.name("lkdungeonlkitems"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<LkdungeonlkitemsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LKDUNGEONLKITEMS__LKDUNGEONLKITEMS_LKDUNGEONID_FKEY, Keys.LKDUNGEONLKITEMS__LKDUNGEONLKITEMS_LKITEMID_FKEY);
    }

    private transient LkdungeonsPath _lkdungeons;

    /**
     * Get the implicit join path to the <code>public.lkdungeons</code> table.
     */
    public LkdungeonsPath lkdungeons() {
        if (_lkdungeons == null)
            _lkdungeons = new LkdungeonsPath(this, Keys.LKDUNGEONLKITEMS__LKDUNGEONLKITEMS_LKDUNGEONID_FKEY, null);

        return _lkdungeons;
    }

    private transient LkitemsPath _lkitems;

    /**
     * Get the implicit join path to the <code>public.lkitems</code> table.
     */
    public LkitemsPath lkitems() {
        if (_lkitems == null)
            _lkitems = new LkitemsPath(this, Keys.LKDUNGEONLKITEMS__LKDUNGEONLKITEMS_LKITEMID_FKEY, null);

        return _lkitems;
    }

    @Override
    public Lkdungeonlkitems as(String alias) {
        return new Lkdungeonlkitems(DSL.name(alias), this);
    }

    @Override
    public Lkdungeonlkitems as(Name alias) {
        return new Lkdungeonlkitems(alias, this);
    }

    @Override
    public Lkdungeonlkitems as(Table<?> alias) {
        return new Lkdungeonlkitems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkdungeonlkitems rename(String name) {
        return new Lkdungeonlkitems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkdungeonlkitems rename(Name name) {
        return new Lkdungeonlkitems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkdungeonlkitems rename(Table<?> name) {
        return new Lkdungeonlkitems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkitems where(Condition condition) {
        return new Lkdungeonlkitems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkitems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkitems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkitems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeonlkitems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeonlkitems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeonlkitems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeonlkitems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkitems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkitems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
