/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.engine.db_generated.Keys;
import space_habit_frontier.engine.db_generated.Public;
import space_habit_frontier.engine.db_generated.tables.records.LkitemsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lkitems extends TableImpl<LkitemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.lkitems</code>
     */
    public static final Lkitems LKITEMS = new Lkitems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LkitemsRecord> getRecordType() {
        return LkitemsRecord.class;
    }

    /**
     * The column <code>public.lkitems.id</code>.
     */
    public final TableField<LkitemsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.lkitems.title</code>.
     */
    public final TableField<LkitemsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.lkitems.exposition</code>.
     */
    public final TableField<LkitemsRecord, String> EXPOSITION = createField(DSL.name("exposition"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.lkitems.cost</code>.
     */
    public final TableField<LkitemsRecord, Integer> COST = createField(DSL.name("cost"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.lkitems.effecttypes</code>.
     */
    public final TableField<LkitemsRecord, Short[]> EFFECTTYPES = createField(DSL.name("effecttypes"), SQLDataType.SMALLINT.array(), this, "");

    /**
     * The column <code>public.lkitems.imageuri</code>.
     */
    public final TableField<LkitemsRecord, String> IMAGEURI = createField(DSL.name("imageuri"), SQLDataType.CLOB, this, "");

    private Lkitems(Name alias, Table<LkitemsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lkitems(Name alias, Table<LkitemsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.lkitems</code> table reference
     */
    public Lkitems(String alias) {
        this(DSL.name(alias), LKITEMS);
    }

    /**
     * Create an aliased <code>public.lkitems</code> table reference
     */
    public Lkitems(Name alias) {
        this(alias, LKITEMS);
    }

    /**
     * Create a <code>public.lkitems</code> table reference
     */
    public Lkitems() {
        this(DSL.name("lkitems"), null);
    }

    public <O extends Record> Lkitems(Table<O> path, ForeignKey<O, LkitemsRecord> childPath, InverseForeignKey<O, LkitemsRecord> parentPath) {
        super(path, childPath, parentPath, LKITEMS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LkitemsPath extends Lkitems implements Path<LkitemsRecord> {
        public <O extends Record> LkitemsPath(Table<O> path, ForeignKey<O, LkitemsRecord> childPath, InverseForeignKey<O, LkitemsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LkitemsPath(Name alias, Table<LkitemsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LkitemsPath as(String alias) {
            return new LkitemsPath(DSL.name(alias), this);
        }

        @Override
        public LkitemsPath as(Name alias) {
            return new LkitemsPath(alias, this);
        }

        @Override
        public LkitemsPath as(Table<?> alias) {
            return new LkitemsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<LkitemsRecord> getPrimaryKey() {
        return Keys.LKITEMS_PKEY;
    }

    @Override
    public Lkitems as(String alias) {
        return new Lkitems(DSL.name(alias), this);
    }

    @Override
    public Lkitems as(Name alias) {
        return new Lkitems(alias, this);
    }

    @Override
    public Lkitems as(Table<?> alias) {
        return new Lkitems(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkitems rename(String name) {
        return new Lkitems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkitems rename(Name name) {
        return new Lkitems(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkitems rename(Table<?> name) {
        return new Lkitems(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkitems where(Condition condition) {
        return new Lkitems(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkitems where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkitems where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkitems where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkitems where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkitems where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkitems where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkitems where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkitems whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkitems whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
