/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.engine.db_generated.Keys;
import space_habit_frontier.engine.db_generated.Public;
import space_habit_frontier.engine.db_generated.tables.records.LkweaponsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lkweapons extends TableImpl<LkweaponsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.lkweapons</code>
     */
    public static final Lkweapons LKWEAPONS = new Lkweapons();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LkweaponsRecord> getRecordType() {
        return LkweaponsRecord.class;
    }

    /**
     * The column <code>public.lkweapons.id</code>.
     */
    public final TableField<LkweaponsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.lkweapons.title</code>.
     */
    public final TableField<LkweaponsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.lkweapons.exposition</code>.
     */
    public final TableField<LkweaponsRecord, String> EXPOSITION = createField(DSL.name("exposition"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.lkweapons.cost</code>.
     */
    public final TableField<LkweaponsRecord, Integer> COST = createField(DSL.name("cost"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.lkweapons.effecttypes</code>.
     */
    public final TableField<LkweaponsRecord, Short[]> EFFECTTYPES = createField(DSL.name("effecttypes"), SQLDataType.SMALLINT.array(), this, "");

    /**
     * The column <code>public.lkweapons.imageuri</code>.
     */
    public final TableField<LkweaponsRecord, String> IMAGEURI = createField(DSL.name("imageuri"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.lkweapons.damagebonus</code>.
     */
    public final TableField<LkweaponsRecord, Short> DAMAGEBONUS = createField(DSL.name("damagebonus"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.lkweapons.absorbbonus</code>.
     */
    public final TableField<LkweaponsRecord, Short> ABSORBBONUS = createField(DSL.name("absorbbonus"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    private Lkweapons(Name alias, Table<LkweaponsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lkweapons(Name alias, Table<LkweaponsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.lkweapons</code> table reference
     */
    public Lkweapons(String alias) {
        this(DSL.name(alias), LKWEAPONS);
    }

    /**
     * Create an aliased <code>public.lkweapons</code> table reference
     */
    public Lkweapons(Name alias) {
        this(alias, LKWEAPONS);
    }

    /**
     * Create a <code>public.lkweapons</code> table reference
     */
    public Lkweapons() {
        this(DSL.name("lkweapons"), null);
    }

    public <O extends Record> Lkweapons(Table<O> path, ForeignKey<O, LkweaponsRecord> childPath, InverseForeignKey<O, LkweaponsRecord> parentPath) {
        super(path, childPath, parentPath, LKWEAPONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LkweaponsPath extends Lkweapons implements Path<LkweaponsRecord> {
        public <O extends Record> LkweaponsPath(Table<O> path, ForeignKey<O, LkweaponsRecord> childPath, InverseForeignKey<O, LkweaponsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LkweaponsPath(Name alias, Table<LkweaponsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LkweaponsPath as(String alias) {
            return new LkweaponsPath(DSL.name(alias), this);
        }

        @Override
        public LkweaponsPath as(Name alias) {
            return new LkweaponsPath(alias, this);
        }

        @Override
        public LkweaponsPath as(Table<?> alias) {
            return new LkweaponsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<LkweaponsRecord> getPrimaryKey() {
        return Keys.LKWEAPONS_PKEY;
    }

    @Override
    public Lkweapons as(String alias) {
        return new Lkweapons(DSL.name(alias), this);
    }

    @Override
    public Lkweapons as(Name alias) {
        return new Lkweapons(alias, this);
    }

    @Override
    public Lkweapons as(Table<?> alias) {
        return new Lkweapons(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkweapons rename(String name) {
        return new Lkweapons(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkweapons rename(Name name) {
        return new Lkweapons(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkweapons rename(Table<?> name) {
        return new Lkweapons(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkweapons where(Condition condition) {
        return new Lkweapons(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkweapons where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkweapons where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkweapons where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkweapons where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkweapons where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkweapons where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkweapons where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkweapons whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkweapons whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
