/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables;


import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.engine.db_generated.Keys;
import space_habit_frontier.engine.db_generated.Public;
import space_habit_frontier.engine.db_generated.tables.Useragents.UseragentsPath;
import space_habit_frontier.engine.db_generated.tables.Users.UsersPath;
import space_habit_frontier.engine.db_generated.tables.records.SecurityeventsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Securityevents extends TableImpl<SecurityeventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.securityevents</code>
     */
    public static final Securityevents SECURITYEVENTS = new Securityevents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SecurityeventsRecord> getRecordType() {
        return SecurityeventsRecord.class;
    }

    /**
     * The column <code>public.securityevents.id</code>.
     */
    public final TableField<SecurityeventsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.securityevents.creationtimestamp</code>.
     */
    public final TableField<SecurityeventsRecord, BigDecimal> CREATIONTIMESTAMP = createField(DSL.name("creationtimestamp"), SQLDataType.NUMERIC(16, 4).nullable(false), this, "");

    /**
     * The column <code>public.securityevents.useragentid</code>.
     */
    public final TableField<SecurityeventsRecord, Long> USERAGENTID = createField(DSL.name("useragentid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.securityevents.userid</code>.
     */
    public final TableField<SecurityeventsRecord, Long> USERID = createField(DSL.name("userid"), SQLDataType.BIGINT, this, "");

    private Securityevents(Name alias, Table<SecurityeventsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Securityevents(Name alias, Table<SecurityeventsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.securityevents</code> table reference
     */
    public Securityevents(String alias) {
        this(DSL.name(alias), SECURITYEVENTS);
    }

    /**
     * Create an aliased <code>public.securityevents</code> table reference
     */
    public Securityevents(Name alias) {
        this(alias, SECURITYEVENTS);
    }

    /**
     * Create a <code>public.securityevents</code> table reference
     */
    public Securityevents() {
        this(DSL.name("securityevents"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<SecurityeventsRecord, Long> getIdentity() {
        return (Identity<SecurityeventsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SecurityeventsRecord> getPrimaryKey() {
        return Keys.SECURITYEVENTS_PKEY;
    }

    @Override
    public List<ForeignKey<SecurityeventsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.SECURITYEVENTS__SECURITYEVENTS_USERAGENTID_FKEY, Keys.SECURITYEVENTS__SECURITYEVENTS_USERID_FKEY);
    }

    private transient UseragentsPath _useragents;

    /**
     * Get the implicit join path to the <code>public.useragents</code> table.
     */
    public UseragentsPath useragents() {
        if (_useragents == null)
            _useragents = new UseragentsPath(this, Keys.SECURITYEVENTS__SECURITYEVENTS_USERAGENTID_FKEY, null);

        return _useragents;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.SECURITYEVENTS__SECURITYEVENTS_USERID_FKEY, null);

        return _users;
    }

    @Override
    public Securityevents as(String alias) {
        return new Securityevents(DSL.name(alias), this);
    }

    @Override
    public Securityevents as(Name alias) {
        return new Securityevents(alias, this);
    }

    @Override
    public Securityevents as(Table<?> alias) {
        return new Securityevents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Securityevents rename(String name) {
        return new Securityevents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Securityevents rename(Name name) {
        return new Securityevents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Securityevents rename(Table<?> name) {
        return new Securityevents(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Securityevents where(Condition condition) {
        return new Securityevents(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Securityevents where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Securityevents where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Securityevents where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Securityevents where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Securityevents where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Securityevents where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Securityevents where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Securityevents whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Securityevents whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
