/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.engine.db_generated.Keys;
import space_habit_frontier.engine.db_generated.Public;
import space_habit_frontier.engine.db_generated.tables.Todos.TodosPath;
import space_habit_frontier.engine.db_generated.tables.Users.UsersPath;
import space_habit_frontier.engine.db_generated.tables.records.TodosRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Todos extends TableImpl<TodosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.todos</code>
     */
    public static final Todos TODOS = new Todos();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TodosRecord> getRecordType() {
        return TodosRecord.class;
    }

    /**
     * The column <code>public.todos.id</code>.
     */
    public final TableField<TodosRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.todos.title</code>.
     */
    public final TableField<TodosRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.todos.note</code>.
     */
    public final TableField<TodosRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.todos.risk</code>.
     */
    public final TableField<TodosRecord, Short> RISK = createField(DSL.name("risk"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("50"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.todos.duedatetimestamp</code>.
     */
    public final TableField<TodosRecord, OffsetDateTime> DUEDATETIMESTAMP = createField(DSL.name("duedatetimestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.todos.effectivedatetimestamp</code>.
     */
    public final TableField<TodosRecord, OffsetDateTime> EFFECTIVEDATETIMESTAMP = createField(DSL.name("effectivedatetimestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.todos.streakstarttimestamp</code>.
     */
    public final TableField<TodosRecord, OffsetDateTime> STREAKSTARTTIMESTAMP = createField(DSL.name("streakstarttimestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.todos.repeatcount</code>.
     */
    public final TableField<TodosRecord, Short> REPEATCOUNT = createField(DSL.name("repeatcount"), SQLDataType.SMALLINT.defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.todos.repeattype</code>.
     */
    public final TableField<TodosRecord, Short> REPEATTYPE = createField(DSL.name("repeattype"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.todos.repeatrate</code>.
     */
    public final TableField<TodosRecord, Short> REPEATRATE = createField(DSL.name("repeatrate"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.todos.weekactivedays</code>.
     */
    public final TableField<TodosRecord, String> WEEKACTIVEDAYS = createField(DSL.name("weekactivedays"), SQLDataType.CHAR(7).nullable(false).defaultValue(DSL.field(DSL.raw("'1111111'::\"bit\""), SQLDataType.CHAR)), this, "");

    /**
     * The column <code>public.todos.yearactivedays</code>.
     */
    public final TableField<TodosRecord, Integer[]> YEARACTIVEDAYS = createField(DSL.name("yearactivedays"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY[]::integer[]"), SQLDataType.INTEGER)).array(), this, "");

    /**
     * The column <code>public.todos.creationtimestamp</code>.
     */
    public final TableField<TodosRecord, OffsetDateTime> CREATIONTIMESTAMP = createField(DSL.name("creationtimestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.todos.userid</code>.
     */
    public final TableField<TodosRecord, UUID> USERID = createField(DSL.name("userid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.todos.parenttodoid</code>.
     */
    public final TableField<TodosRecord, UUID> PARENTTODOID = createField(DSL.name("parenttodoid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.todos.monthactivedays</code>.
     */
    public final TableField<TodosRecord, Integer[]> MONTHACTIVEDAYS = createField(DSL.name("monthactivedays"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY[]::integer[]"), SQLDataType.INTEGER)).array(), this, "");

    /**
     * The column <code>public.todos.poisonous</code>.
     */
    public final TableField<TodosRecord, Boolean> POISONOUS = createField(DSL.name("poisonous"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.todos.expirationdatetimestamp</code>.
     */
    public final TableField<TodosRecord, OffsetDateTime> EXPIRATIONDATETIMESTAMP = createField(DSL.name("expirationdatetimestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6), this, "");

    /**
     * The column <code>public.todos.rateinversionflag</code>.
     */
    public final TableField<TodosRecord, Boolean> RATEINVERSIONFLAG = createField(DSL.name("rateinversionflag"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "");

    private Todos(Name alias, Table<TodosRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Todos(Name alias, Table<TodosRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.todos</code> table reference
     */
    public Todos(String alias) {
        this(DSL.name(alias), TODOS);
    }

    /**
     * Create an aliased <code>public.todos</code> table reference
     */
    public Todos(Name alias) {
        this(alias, TODOS);
    }

    /**
     * Create a <code>public.todos</code> table reference
     */
    public Todos() {
        this(DSL.name("todos"), null);
    }

    public <O extends Record> Todos(Table<O> path, ForeignKey<O, TodosRecord> childPath, InverseForeignKey<O, TodosRecord> parentPath) {
        super(path, childPath, parentPath, TODOS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class TodosPath extends Todos implements Path<TodosRecord> {
        public <O extends Record> TodosPath(Table<O> path, ForeignKey<O, TodosRecord> childPath, InverseForeignKey<O, TodosRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private TodosPath(Name alias, Table<TodosRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public TodosPath as(String alias) {
            return new TodosPath(DSL.name(alias), this);
        }

        @Override
        public TodosPath as(Name alias) {
            return new TodosPath(alias, this);
        }

        @Override
        public TodosPath as(Table<?> alias) {
            return new TodosPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TodosRecord> getPrimaryKey() {
        return Keys.TODOS_PKEY;
    }

    @Override
    public List<ForeignKey<TodosRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TODOS__TODOS_USERID_FKEY, Keys.TODOS__TODOS_PARENTTODOID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.TODOS__TODOS_USERID_FKEY, null);

        return _users;
    }

    private transient TodosPath _todos;

    /**
     * Get the implicit join path to the <code>public.todos</code> table.
     */
    public TodosPath todos() {
        if (_todos == null)
            _todos = new TodosPath(this, Keys.TODOS__TODOS_PARENTTODOID_FKEY, null);

        return _todos;
    }

    @Override
    public Todos as(String alias) {
        return new Todos(DSL.name(alias), this);
    }

    @Override
    public Todos as(Name alias) {
        return new Todos(alias, this);
    }

    @Override
    public Todos as(Table<?> alias) {
        return new Todos(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Todos rename(String name) {
        return new Todos(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todos rename(Name name) {
        return new Todos(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todos rename(Table<?> name) {
        return new Todos(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos where(Condition condition) {
        return new Todos(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todos where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todos where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todos where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todos where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todos whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
