/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.engine.db_generated.Keys;
import space_habit_frontier.engine.db_generated.Public;
import space_habit_frontier.engine.db_generated.tables.records.UseragentsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Useragents extends TableImpl<UseragentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.useragents</code>
     */
    public static final Useragents USERAGENTS = new Useragents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UseragentsRecord> getRecordType() {
        return UseragentsRecord.class;
    }

    /**
     * The column <code>public.useragents.id</code>.
     */
    public final TableField<UseragentsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.useragents.contents</code>.
     */
    public final TableField<UseragentsRecord, String> CONTENTS = createField(DSL.name("contents"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.useragents.ualength</code>.
     */
    public final TableField<UseragentsRecord, Short> UALENGTH = createField(DSL.name("ualength"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.useragents.uahash</code>.
     */
    public final TableField<UseragentsRecord, byte[]> UAHASH = createField(DSL.name("uahash"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>public.useragents.ipv4address</code>.
     */
    public final TableField<UseragentsRecord, String> IPV4ADDRESS = createField(DSL.name("ipv4address"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.useragents.ipv6address</code>.
     */
    public final TableField<UseragentsRecord, String> IPV6ADDRESS = createField(DSL.name("ipv6address"), SQLDataType.CLOB, this, "");

    private Useragents(Name alias, Table<UseragentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Useragents(Name alias, Table<UseragentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.useragents</code> table reference
     */
    public Useragents(String alias) {
        this(DSL.name(alias), USERAGENTS);
    }

    /**
     * Create an aliased <code>public.useragents</code> table reference
     */
    public Useragents(Name alias) {
        this(alias, USERAGENTS);
    }

    /**
     * Create a <code>public.useragents</code> table reference
     */
    public Useragents() {
        this(DSL.name("useragents"), null);
    }

    public <O extends Record> Useragents(Table<O> path, ForeignKey<O, UseragentsRecord> childPath, InverseForeignKey<O, UseragentsRecord> parentPath) {
        super(path, childPath, parentPath, USERAGENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UseragentsPath extends Useragents implements Path<UseragentsRecord> {
        public <O extends Record> UseragentsPath(Table<O> path, ForeignKey<O, UseragentsRecord> childPath, InverseForeignKey<O, UseragentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UseragentsPath(Name alias, Table<UseragentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UseragentsPath as(String alias) {
            return new UseragentsPath(DSL.name(alias), this);
        }

        @Override
        public UseragentsPath as(Name alias) {
            return new UseragentsPath(alias, this);
        }

        @Override
        public UseragentsPath as(Table<?> alias) {
            return new UseragentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<UseragentsRecord, Long> getIdentity() {
        return (Identity<UseragentsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UseragentsRecord> getPrimaryKey() {
        return Keys.USERAGENTS_PKEY;
    }

    @Override
    public Useragents as(String alias) {
        return new Useragents(DSL.name(alias), this);
    }

    @Override
    public Useragents as(Name alias) {
        return new Useragents(alias, this);
    }

    @Override
    public Useragents as(Table<?> alias) {
        return new Useragents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Useragents rename(String name) {
        return new Useragents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Useragents rename(Name name) {
        return new Useragents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Useragents rename(Table<?> name) {
        return new Useragents(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Useragents where(Condition condition) {
        return new Useragents(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Useragents where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Useragents where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Useragents where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Useragents where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Useragents where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Useragents where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Useragents where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Useragents whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Useragents whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
