/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.engine.db_generated.Keys;
import space_habit_frontier.engine.db_generated.Public;
import space_habit_frontier.engine.db_generated.tables.records.VisitorsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Visitors extends TableImpl<VisitorsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.visitors</code>
     */
    public static final Visitors VISITORS = new Visitors();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VisitorsRecord> getRecordType() {
        return VisitorsRecord.class;
    }

    /**
     * The column <code>public.visitors.id</code>.
     */
    public final TableField<VisitorsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.visitors.contents</code>.
     */
    public final TableField<VisitorsRecord, String> CONTENTS = createField(DSL.name("contents"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.visitors.ualength</code>.
     */
    public final TableField<VisitorsRecord, Short> UALENGTH = createField(DSL.name("ualength"), SQLDataType.SMALLINT.nullable(false), this, "");

    /**
     * The column <code>public.visitors.uahash</code>.
     */
    public final TableField<VisitorsRecord, byte[]> UAHASH = createField(DSL.name("uahash"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>public.visitors.ipv4address</code>.
     */
    public final TableField<VisitorsRecord, String> IPV4ADDRESS = createField(DSL.name("ipv4address"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.visitors.ipv6address</code>.
     */
    public final TableField<VisitorsRecord, String> IPV6ADDRESS = createField(DSL.name("ipv6address"), SQLDataType.CLOB, this, "");

    private Visitors(Name alias, Table<VisitorsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Visitors(Name alias, Table<VisitorsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.visitors</code> table reference
     */
    public Visitors(String alias) {
        this(DSL.name(alias), VISITORS);
    }

    /**
     * Create an aliased <code>public.visitors</code> table reference
     */
    public Visitors(Name alias) {
        this(alias, VISITORS);
    }

    /**
     * Create a <code>public.visitors</code> table reference
     */
    public Visitors() {
        this(DSL.name("visitors"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<VisitorsRecord, Long> getIdentity() {
        return (Identity<VisitorsRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<VisitorsRecord> getPrimaryKey() {
        return Keys.VISTORS_PKEY;
    }

    @Override
    public Visitors as(String alias) {
        return new Visitors(DSL.name(alias), this);
    }

    @Override
    public Visitors as(Name alias) {
        return new Visitors(alias, this);
    }

    @Override
    public Visitors as(Table<?> alias) {
        return new Visitors(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Visitors rename(String name) {
        return new Visitors(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Visitors rename(Name name) {
        return new Visitors(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Visitors rename(Table<?> name) {
        return new Visitors(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Visitors where(Condition condition) {
        return new Visitors(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Visitors where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Visitors where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Visitors where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Visitors where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Visitors where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Visitors where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Visitors where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Visitors whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Visitors whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
