/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Actions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActionsRecord extends UpdatableRecordImpl<ActionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.actions.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.actions.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.actions.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.actions.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.actions.note</code>.
     */
    public void setNote(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.actions.note</code>.
     */
    public String getNote() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.actions.risk</code>.
     */
    public void setRisk(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.actions.risk</code>.
     */
    public Short getRisk() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.actions.freeviolations</code>.
     */
    public void setFreeviolations(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.actions.freeviolations</code>.
     */
    public Short getFreeviolations() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.actions.orientationtype</code>.
     */
    public void setOrientationtype(Short value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.actions.orientationtype</code>.
     */
    public Short getOrientationtype() {
        return (Short) get(5);
    }

    /**
     * Setter for <code>public.actions.maxcount</code>.
     */
    public void setMaxcount(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.actions.maxcount</code>.
     */
    public Short getMaxcount() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.actions.userid</code>.
     */
    public void setUserid(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.actions.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActionsRecord
     */
    public ActionsRecord() {
        super(Actions.ACTIONS);
    }

    /**
     * Create a detached, initialised ActionsRecord
     */
    public ActionsRecord(Long id, String title, String note, Short risk, Short freeviolations, Short orientationtype, Short maxcount, Long userid) {
        super(Actions.ACTIONS);

        setId(id);
        setTitle(title);
        setNote(note);
        setRisk(risk);
        setFreeviolations(freeviolations);
        setOrientationtype(orientationtype);
        setMaxcount(maxcount);
        setUserid(userid);
        resetChangedOnNotNull();
    }
}
