/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Actionevents;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActioneventsRecord extends UpdatableRecordImpl<ActioneventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.actionevents.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.actionevents.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.actionevents.damage</code>.
     */
    public void setDamage(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.actionevents.damage</code>.
     */
    public Integer getDamage() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.actionevents.creationtimestamp</code>.
     */
    public void setCreationtimestamp(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.actionevents.creationtimestamp</code>.
     */
    public BigDecimal getCreationtimestamp() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.actionevents.actionid</code>.
     */
    public void setActionid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.actionevents.actionid</code>.
     */
    public Long getActionid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.actionevents.userid</code>.
     */
    public void setUserid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.actionevents.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActioneventsRecord
     */
    public ActioneventsRecord() {
        super(Actionevents.ACTIONEVENTS);
    }

    /**
     * Create a detached, initialised ActioneventsRecord
     */
    public ActioneventsRecord(Long id, Integer damage, BigDecimal creationtimestamp, Long actionid, Long userid) {
        super(Actionevents.ACTIONEVENTS);

        setId(id);
        setDamage(damage);
        setCreationtimestamp(creationtimestamp);
        setActionid(actionid);
        setUserid(userid);
        resetChangedOnNotNull();
    }
}
