/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Adventureevents;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdventureeventsRecord extends UpdatableRecordImpl<AdventureeventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.adventureevents.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.adventureevents.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.adventureevents.eventtype</code>.
     */
    public void setEventtype(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.adventureevents.eventtype</code>.
     */
    public Short getEventtype() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.adventureevents.creationtimestamp</code>.
     */
    public void setCreationtimestamp(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.adventureevents.creationtimestamp</code>.
     */
    public BigDecimal getCreationtimestamp() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.adventureevents.userid</code>.
     */
    public void setUserid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.adventureevents.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdventureeventsRecord
     */
    public AdventureeventsRecord() {
        super(Adventureevents.ADVENTUREEVENTS);
    }

    /**
     * Create a detached, initialised AdventureeventsRecord
     */
    public AdventureeventsRecord(Long id, Short eventtype, BigDecimal creationtimestamp, Long userid) {
        super(Adventureevents.ADVENTUREEVENTS);

        setId(id);
        setEventtype(eventtype);
        setCreationtimestamp(creationtimestamp);
        setUserid(userid);
        resetChangedOnNotNull();
    }
}
