/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Dungeon;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DungeonRecord extends UpdatableRecordImpl<DungeonRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.dungeon.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.dungeon.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.dungeon.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.dungeon.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setCoordinates(Object value) {
        set(2, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getCoordinates() {
        return get(2);
    }

    /**
     * Setter for <code>public.dungeon.lvl</code>.
     */
    public void setLvl(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.dungeon.lvl</code>.
     */
    public Integer getLvl() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.dungeon.lkdungeonid</code>.
     */
    public void setLkdungeonid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.dungeon.lkdungeonid</code>.
     */
    public Long getLkdungeonid() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>public.dungeon.userid</code>.
     */
    public void setUserid(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.dungeon.userid</code>.
     */
    public UUID getUserid() {
        return (UUID) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DungeonRecord
     */
    public DungeonRecord() {
        super(Dungeon.DUNGEON);
    }

    /**
     * Create a detached, initialised DungeonRecord
     */
    public DungeonRecord(Long id, String title, Object coordinates, Integer lvl, Long lkdungeonid, UUID userid) {
        super(Dungeon.DUNGEON);

        setId(id);
        setTitle(title);
        setCoordinates(coordinates);
        setLvl(lvl);
        setLkdungeonid(lkdungeonid);
        setUserid(userid);
        resetChangedOnNotNull();
    }
}
