/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSON;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Hero;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class HeroRecord extends UpdatableRecordImpl<HeroRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.hero.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.hero.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.hero.xp</code>.
     */
    public void setXp(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.hero.xp</code>.
     */
    public Long getXp() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.hero.gold</code>.
     */
    public void setGold(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.hero.gold</code>.
     */
    public Long getGold() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.hero.inventory</code>.
     */
    public void setInventory(JSON value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.hero.inventory</code>.
     */
    public JSON getInventory() {
        return (JSON) get(3);
    }

    /**
     * Setter for <code>public.hero.monster</code>.
     */
    public void setMonster(JSON value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.hero.monster</code>.
     */
    public JSON getMonster() {
        return (JSON) get(4);
    }

    /**
     * Setter for <code>public.hero.dungeon</code>.
     */
    public void setDungeon(JSON value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.hero.dungeon</code>.
     */
    public JSON getDungeon() {
        return (JSON) get(5);
    }

    /**
     * Setter for <code>public.hero.currenthp</code>.
     */
    public void setCurrenthp(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.hero.currenthp</code>.
     */
    public Long getCurrenthp() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.hero.activebonustypes</code>.
     */
    public void setActivebonustypes(Short[] value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.hero.activebonustypes</code>.
     */
    public Short[] getActivebonustypes() {
        return (Short[]) get(7);
    }

    /**
     * Setter for <code>public.hero.activepenaltytypes</code>.
     */
    public void setActivepenaltytypes(Short[] value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.hero.activepenaltytypes</code>.
     */
    public Short[] getActivepenaltytypes() {
        return (Short[]) get(8);
    }

    /**
     * Setter for <code>public.hero.weaponrightid</code>.
     */
    public void setWeaponrightid(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.hero.weaponrightid</code>.
     */
    public Long getWeaponrightid() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>public.hero.weaponleftid</code>.
     */
    public void setWeaponleftid(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.hero.weaponleftid</code>.
     */
    public Long getWeaponleftid() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>public.hero.frontarmorid</code>.
     */
    public void setFrontarmorid(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.hero.frontarmorid</code>.
     */
    public Long getFrontarmorid() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.hero.backarmorid</code>.
     */
    public void setBackarmorid(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.hero.backarmorid</code>.
     */
    public Long getBackarmorid() {
        return (Long) get(12);
    }

    /**
     * Setter for <code>public.hero.toparmorid</code>.
     */
    public void setToparmorid(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.hero.toparmorid</code>.
     */
    public Long getToparmorid() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>public.hero.bottomarmorid</code>.
     */
    public void setBottomarmorid(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.hero.bottomarmorid</code>.
     */
    public Long getBottomarmorid() {
        return (Long) get(14);
    }

    /**
     * Setter for <code>public.hero.touchedtimestamp</code>.
     */
    public void setTouchedtimestamp(OffsetDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.hero.touchedtimestamp</code>.
     */
    public OffsetDateTime getTouchedtimestamp() {
        return (OffsetDateTime) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached HeroRecord
     */
    public HeroRecord() {
        super(Hero.HERO);
    }

    /**
     * Create a detached, initialised HeroRecord
     */
    public HeroRecord(UUID id, Long xp, Long gold, JSON inventory, JSON monster, JSON dungeon, Long currenthp, Short[] activebonustypes, Short[] activepenaltytypes, Long weaponrightid, Long weaponleftid, Long frontarmorid, Long backarmorid, Long toparmorid, Long bottomarmorid, OffsetDateTime touchedtimestamp) {
        super(Hero.HERO);

        setId(id);
        setXp(xp);
        setGold(gold);
        setInventory(inventory);
        setMonster(monster);
        setDungeon(dungeon);
        setCurrenthp(currenthp);
        setActivebonustypes(activebonustypes);
        setActivepenaltytypes(activepenaltytypes);
        setWeaponrightid(weaponrightid);
        setWeaponleftid(weaponleftid);
        setFrontarmorid(frontarmorid);
        setBackarmorid(backarmorid);
        setToparmorid(toparmorid);
        setBottomarmorid(bottomarmorid);
        setTouchedtimestamp(touchedtimestamp);
        resetChangedOnNotNull();
    }
}
