/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import org.jooq.impl.TableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Lkdungeonlkmonsters;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LkdungeonlkmonstersRecord extends TableRecordImpl<LkdungeonlkmonstersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lkdungeonlkmonsters.lkdungeonid</code>.
     */
    public void setLkdungeonid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lkdungeonlkmonsters.lkdungeonid</code>.
     */
    public Long getLkdungeonid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.lkdungeonlkmonsters.lkmonsterid</code>.
     */
    public void setLkmonsterid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lkdungeonlkmonsters.lkmonsterid</code>.
     */
    public Long getLkmonsterid() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LkdungeonlkmonstersRecord
     */
    public LkdungeonlkmonstersRecord() {
        super(Lkdungeonlkmonsters.LKDUNGEONLKMONSTERS);
    }

    /**
     * Create a detached, initialised LkdungeonlkmonstersRecord
     */
    public LkdungeonlkmonstersRecord(Long lkdungeonid, Long lkmonsterid) {
        super(Lkdungeonlkmonsters.LKDUNGEONLKMONSTERS);

        setLkdungeonid(lkdungeonid);
        setLkmonsterid(lkmonsterid);
        resetChangedOnNotNull();
    }
}
