/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import org.jooq.impl.TableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Lkdungeonlkitems;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LkdungeonlkitemsRecord extends TableRecordImpl<LkdungeonlkitemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lkdungeonlkitems.lkdungeonid</code>.
     */
    public void setLkdungeonid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lkdungeonlkitems.lkdungeonid</code>.
     */
    public Long getLkdungeonid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.lkdungeonlkitems.lkitemid</code>.
     */
    public void setLkitemid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lkdungeonlkitems.lkitemid</code>.
     */
    public Long getLkitemid() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LkdungeonlkitemsRecord
     */
    public LkdungeonlkitemsRecord() {
        super(Lkdungeonlkitems.LKDUNGEONLKITEMS);
    }

    /**
     * Create a detached, initialised LkdungeonlkitemsRecord
     */
    public LkdungeonlkitemsRecord(Long lkdungeonid, Long lkitemid) {
        super(Lkdungeonlkitems.LKDUNGEONLKITEMS);

        setLkdungeonid(lkdungeonid);
        setLkitemid(lkitemid);
        resetChangedOnNotNull();
    }
}
