/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Lkdungeons;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LkdungeonsRecord extends UpdatableRecordImpl<LkdungeonsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lkdungeons.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lkdungeons.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.lkdungeons.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lkdungeons.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lkdungeons.exposition</code>.
     */
    public void setExposition(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lkdungeons.exposition</code>.
     */
    public String getExposition() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lkdungeons.minlvl</code>.
     */
    public void setMinlvl(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lkdungeons.minlvl</code>.
     */
    public Short getMinlvl() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.lkdungeons.imageuri</code>.
     */
    public void setImageuri(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lkdungeons.imageuri</code>.
     */
    public String getImageuri() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LkdungeonsRecord
     */
    public LkdungeonsRecord() {
        super(Lkdungeons.LKDUNGEONS);
    }

    /**
     * Create a detached, initialised LkdungeonsRecord
     */
    public LkdungeonsRecord(Long id, String title, String exposition, Short minlvl, String imageuri) {
        super(Lkdungeons.LKDUNGEONS);

        setId(id);
        setTitle(title);
        setExposition(exposition);
        setMinlvl(minlvl);
        setImageuri(imageuri);
        resetChangedOnNotNull();
    }
}
