/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Lkmonsters;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LkmonstersRecord extends UpdatableRecordImpl<LkmonstersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lkmonsters.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lkmonsters.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.lkmonsters.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lkmonsters.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lkmonsters.exposition</code>.
     */
    public void setExposition(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lkmonsters.exposition</code>.
     */
    public String getExposition() {
        return (String) get(2);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public void setLvlrange(Object value) {
        set(3, value);
    }

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public Object getLvlrange() {
        return get(3);
    }

    /**
     * Setter for <code>public.lkmonsters.xpmultiplier</code>.
     */
    public void setXpmultiplier(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lkmonsters.xpmultiplier</code>.
     */
    public Short getXpmultiplier() {
        return (Short) get(4);
    }

    /**
     * Setter for <code>public.lkmonsters.imageuri</code>.
     */
    public void setImageuri(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lkmonsters.imageuri</code>.
     */
    public String getImageuri() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LkmonstersRecord
     */
    public LkmonstersRecord() {
        super(Lkmonsters.LKMONSTERS);
    }

    /**
     * Create a detached, initialised LkmonstersRecord
     */
    public LkmonstersRecord(Long id, String title, String exposition, Object lvlrange, Short xpmultiplier, String imageuri) {
        super(Lkmonsters.LKMONSTERS);

        setId(id);
        setTitle(title);
        setExposition(exposition);
        setLvlrange(lvlrange);
        setXpmultiplier(xpmultiplier);
        setImageuri(imageuri);
        resetChangedOnNotNull();
    }
}
