/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Lkweapons;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LkweaponsRecord extends UpdatableRecordImpl<LkweaponsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lkweapons.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lkweapons.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.lkweapons.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lkweapons.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lkweapons.exposition</code>.
     */
    public void setExposition(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lkweapons.exposition</code>.
     */
    public String getExposition() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lkweapons.cost</code>.
     */
    public void setCost(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lkweapons.cost</code>.
     */
    public Integer getCost() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.lkweapons.effecttypes</code>.
     */
    public void setEffecttypes(Short[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lkweapons.effecttypes</code>.
     */
    public Short[] getEffecttypes() {
        return (Short[]) get(4);
    }

    /**
     * Setter for <code>public.lkweapons.imageuri</code>.
     */
    public void setImageuri(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lkweapons.imageuri</code>.
     */
    public String getImageuri() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.lkweapons.damagebonus</code>.
     */
    public void setDamagebonus(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lkweapons.damagebonus</code>.
     */
    public Short getDamagebonus() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.lkweapons.absorbbonus</code>.
     */
    public void setAbsorbbonus(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.lkweapons.absorbbonus</code>.
     */
    public Short getAbsorbbonus() {
        return (Short) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LkweaponsRecord
     */
    public LkweaponsRecord() {
        super(Lkweapons.LKWEAPONS);
    }

    /**
     * Create a detached, initialised LkweaponsRecord
     */
    public LkweaponsRecord(Long id, String title, String exposition, Integer cost, Short[] effecttypes, String imageuri, Short damagebonus, Short absorbbonus) {
        super(Lkweapons.LKWEAPONS);

        setId(id);
        setTitle(title);
        setExposition(exposition);
        setCost(cost);
        setEffecttypes(effecttypes);
        setImageuri(imageuri);
        setDamagebonus(damagebonus);
        setAbsorbbonus(absorbbonus);
        resetChangedOnNotNull();
    }
}
