/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Securityevents;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SecurityeventsRecord extends UpdatableRecordImpl<SecurityeventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.securityevents.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.securityevents.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.securityevents.creationtimestamp</code>.
     */
    public void setCreationtimestamp(BigDecimal value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.securityevents.creationtimestamp</code>.
     */
    public BigDecimal getCreationtimestamp() {
        return (BigDecimal) get(1);
    }

    /**
     * Setter for <code>public.securityevents.useragentid</code>.
     */
    public void setUseragentid(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.securityevents.useragentid</code>.
     */
    public Long getUseragentid() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>public.securityevents.userid</code>.
     */
    public void setUserid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.securityevents.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecurityeventsRecord
     */
    public SecurityeventsRecord() {
        super(Securityevents.SECURITYEVENTS);
    }

    /**
     * Create a detached, initialised SecurityeventsRecord
     */
    public SecurityeventsRecord(Long id, BigDecimal creationtimestamp, Long useragentid, Long userid) {
        super(Securityevents.SECURITYEVENTS);

        setId(id);
        setCreationtimestamp(creationtimestamp);
        setUseragentid(useragentid);
        setUserid(userid);
        resetChangedOnNotNull();
    }
}
