/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Todos;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TodosRecord extends UpdatableRecordImpl<TodosRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.todos.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.todos.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.todos.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.todos.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.todos.note</code>.
     */
    public void setNote(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.todos.note</code>.
     */
    public String getNote() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.todos.risk</code>.
     */
    public void setRisk(Short value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.todos.risk</code>.
     */
    public Short getRisk() {
        return (Short) get(3);
    }

    /**
     * Setter for <code>public.todos.duedatetimestamp</code>.
     */
    public void setDuedatetimestamp(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.todos.duedatetimestamp</code>.
     */
    public BigDecimal getDuedatetimestamp() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>public.todos.effectivedatetimestamp</code>.
     */
    public void setEffectivedatetimestamp(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.todos.effectivedatetimestamp</code>.
     */
    public BigDecimal getEffectivedatetimestamp() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>public.todos.streakstarttimestamp</code>.
     */
    public void setStreakstarttimestamp(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.todos.streakstarttimestamp</code>.
     */
    public BigDecimal getStreakstarttimestamp() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>public.todos.repeatcount</code>.
     */
    public void setRepeatcount(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.todos.repeatcount</code>.
     */
    public Short getRepeatcount() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>public.todos.repeattype</code>.
     */
    public void setRepeattype(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.todos.repeattype</code>.
     */
    public Short getRepeattype() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>public.todos.repeatrate</code>.
     */
    public void setRepeatrate(Short value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.todos.repeatrate</code>.
     */
    public Short getRepeatrate() {
        return (Short) get(9);
    }

    /**
     * Setter for <code>public.todos.weekactivedays</code>.
     */
    public void setWeekactivedays(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.todos.weekactivedays</code>.
     */
    public String getWeekactivedays() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.todos.yearactivedays</code>.
     */
    public void setYearactivedays(Integer[] value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.todos.yearactivedays</code>.
     */
    public Integer[] getYearactivedays() {
        return (Integer[]) get(11);
    }

    /**
     * Setter for <code>public.todos.creationtimestamp</code>.
     */
    public void setCreationtimestamp(BigDecimal value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.todos.creationtimestamp</code>.
     */
    public BigDecimal getCreationtimestamp() {
        return (BigDecimal) get(12);
    }

    /**
     * Setter for <code>public.todos.userid</code>.
     */
    public void setUserid(Long value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.todos.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(13);
    }

    /**
     * Setter for <code>public.todos.parenttodoid</code>.
     */
    public void setParenttodoid(Long value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.todos.parenttodoid</code>.
     */
    public Long getParenttodoid() {
        return (Long) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TodosRecord
     */
    public TodosRecord() {
        super(Todos.TODOS);
    }

    /**
     * Create a detached, initialised TodosRecord
     */
    public TodosRecord(Long id, String title, String note, Short risk, BigDecimal duedatetimestamp, BigDecimal effectivedatetimestamp, BigDecimal streakstarttimestamp, Short repeatcount, Short repeattype, Short repeatrate, String weekactivedays, Integer[] yearactivedays, BigDecimal creationtimestamp, Long userid, Long parenttodoid) {
        super(Todos.TODOS);

        setId(id);
        setTitle(title);
        setNote(note);
        setRisk(risk);
        setDuedatetimestamp(duedatetimestamp);
        setEffectivedatetimestamp(effectivedatetimestamp);
        setStreakstarttimestamp(streakstarttimestamp);
        setRepeatcount(repeatcount);
        setRepeattype(repeattype);
        setRepeatrate(repeatrate);
        setWeekactivedays(weekactivedays);
        setYearactivedays(yearactivedays);
        setCreationtimestamp(creationtimestamp);
        setUserid(userid);
        setParenttodoid(parenttodoid);
        resetChangedOnNotNull();
    }
}
