/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import java.math.BigDecimal;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Todoevents;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TodoeventsRecord extends UpdatableRecordImpl<TodoeventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.todoevents.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.todoevents.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.todoevents.damage</code>.
     */
    public void setDamage(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.todoevents.damage</code>.
     */
    public Integer getDamage() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.todoevents.creationtimestamp</code>.
     */
    public void setCreationtimestamp(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.todoevents.creationtimestamp</code>.
     */
    public BigDecimal getCreationtimestamp() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.todoevents.todoid</code>.
     */
    public void setTodoid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.todoevents.todoid</code>.
     */
    public Long getTodoid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>public.todoevents.userid</code>.
     */
    public void setUserid(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.todoevents.userid</code>.
     */
    public Long getUserid() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TodoeventsRecord
     */
    public TodoeventsRecord() {
        super(Todoevents.TODOEVENTS);
    }

    /**
     * Create a detached, initialised TodoeventsRecord
     */
    public TodoeventsRecord(Long id, Integer damage, BigDecimal creationtimestamp, Long todoid, Long userid) {
        super(Todoevents.TODOEVENTS);

        setId(id);
        setDamage(damage);
        setCreationtimestamp(creationtimestamp);
        setTodoid(todoid);
        setUserid(userid);
        resetChangedOnNotNull();
    }
}
