/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Useragents;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UseragentsRecord extends UpdatableRecordImpl<UseragentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.useragents.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.useragents.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.useragents.contents</code>.
     */
    public void setContents(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.useragents.contents</code>.
     */
    public String getContents() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.useragents.ualength</code>.
     */
    public void setUalength(Short value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.useragents.ualength</code>.
     */
    public Short getUalength() {
        return (Short) get(2);
    }

    /**
     * Setter for <code>public.useragents.uahash</code>.
     */
    public void setUahash(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.useragents.uahash</code>.
     */
    public byte[] getUahash() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>public.useragents.ipv4address</code>.
     */
    public void setIpv4address(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.useragents.ipv4address</code>.
     */
    public String getIpv4address() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.useragents.ipv6address</code>.
     */
    public void setIpv6address(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.useragents.ipv6address</code>.
     */
    public String getIpv6address() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UseragentsRecord
     */
    public UseragentsRecord() {
        super(Useragents.USERAGENTS);
    }

    /**
     * Create a detached, initialised UseragentsRecord
     */
    public UseragentsRecord(Long id, String contents, Short ualength, byte[] uahash, String ipv4address, String ipv6address) {
        super(Useragents.USERAGENTS);

        setId(id);
        setContents(contents);
        setUalength(ualength);
        setUahash(uahash);
        setIpv4address(ipv4address);
        setIpv6address(ipv6address);
        resetChangedOnNotNull();
    }
}
