/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Users;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.users.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.hashedpw</code>.
     */
    public void setHashedpw(byte[] value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.hashedpw</code>.
     */
    public byte[] getHashedpw() {
        return (byte[]) get(3);
    }

    /**
     * Setter for <code>public.users.conditioncode</code>.
     */
    public void setConditioncode(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.conditioncode</code>.
     */
    public Integer getConditioncode() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.users.creationtimestamp</code>.
     */
    public void setCreationtimestamp(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.creationtimestamp</code>.
     */
    public OffsetDateTime getCreationtimestamp() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.users.daystart</code>.
     */
    public void setDaystart(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users.daystart</code>.
     */
    public Short getDaystart() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.users.deathgoldpenalty</code>.
     */
    public void setDeathgoldpenalty(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users.deathgoldpenalty</code>.
     */
    public Integer getDeathgoldpenalty() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.users.deathlvlpenalty</code>.
     */
    public void setDeathlvlpenalty(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users.deathlvlpenalty</code>.
     */
    public Integer getDeathlvlpenalty() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.users.adventuremode</code>.
     */
    public void setAdventuremode(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.users.adventuremode</code>.
     */
    public Integer getAdventuremode() {
        return (Integer) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(UUID id, String username, String email, byte[] hashedpw, Integer conditioncode, OffsetDateTime creationtimestamp, Short daystart, Integer deathgoldpenalty, Integer deathlvlpenalty, Integer adventuremode) {
        super(Users.USERS);

        setId(id);
        setUsername(username);
        setEmail(email);
        setHashedpw(hashedpw);
        setConditioncode(conditioncode);
        setCreationtimestamp(creationtimestamp);
        setDaystart(daystart);
        setDeathgoldpenalty(deathgoldpenalty);
        setDeathlvlpenalty(deathlvlpenalty);
        setAdventuremode(adventuremode);
        resetChangedOnNotNull();
    }
}
