/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.engine.db_generated.tables.Usersessions;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersessionsRecord extends UpdatableRecordImpl<UsersessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.usersessions.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.usersessions.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.usersessions.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.usersessions.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.usersessions.creationtimestamp</code>.
     */
    public void setCreationtimestamp(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.usersessions.creationtimestamp</code>.
     */
    public OffsetDateTime getCreationtimestamp() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.usersessions.expirationtimestamp</code>.
     */
    public void setExpirationtimestamp(OffsetDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.usersessions.expirationtimestamp</code>.
     */
    public OffsetDateTime getExpirationtimestamp() {
        return (OffsetDateTime) get(3);
    }

    /**
     * Setter for <code>public.usersessions.userid</code>.
     */
    public void setUserid(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.usersessions.userid</code>.
     */
    public UUID getUserid() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.usersessions.visitorid</code>.
     */
    public void setVisitorid(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.usersessions.visitorid</code>.
     */
    public Long getVisitorid() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersessionsRecord
     */
    public UsersessionsRecord() {
        super(Usersessions.USERSESSIONS);
    }

    /**
     * Create a detached, initialised UsersessionsRecord
     */
    public UsersessionsRecord(UUID id, String username, OffsetDateTime creationtimestamp, OffsetDateTime expirationtimestamp, UUID userid, Long visitorid) {
        super(Usersessions.USERSESSIONS);

        setId(id);
        setUsername(username);
        setCreationtimestamp(creationtimestamp);
        setExpirationtimestamp(expirationtimestamp);
        setUserid(userid);
        setVisitorid(visitorid);
        resetChangedOnNotNull();
    }
}
