/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.data_model.db_generated.tables.Actionevents;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ActioneventsRecord extends UpdatableRecordImpl<ActioneventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.actionevents.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.actionevents.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.actionevents.damage</code>.
     */
    public void setDamage(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.actionevents.damage</code>.
     */
    public Integer getDamage() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.actionevents.creationtimestamp</code>.
     */
    public void setCreationtimestamp(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.actionevents.creationtimestamp</code>.
     */
    public OffsetDateTime getCreationtimestamp() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.actionevents.actionid</code>.
     */
    public void setActionid(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.actionevents.actionid</code>.
     */
    public UUID getActionid() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.actionevents.userid</code>.
     */
    public void setUserid(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.actionevents.userid</code>.
     */
    public UUID getUserid() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActioneventsRecord
     */
    public ActioneventsRecord() {
        super(Actionevents.ACTIONEVENTS);
    }

    /**
     * Create a detached, initialised ActioneventsRecord
     */
    public ActioneventsRecord(UUID id, Integer damage, OffsetDateTime creationtimestamp, UUID actionid, UUID userid) {
        super(Actionevents.ACTIONEVENTS);

        setId(id);
        setDamage(damage);
        setCreationtimestamp(creationtimestamp);
        setActionid(actionid);
        setUserid(userid);
        resetChangedOnNotNull();
    }
}
