/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.data_model.db_generated.tables.Adventureevents;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AdventureeventsRecord extends UpdatableRecordImpl<AdventureeventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.adventureevents.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.adventureevents.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.adventureevents.eventtype</code>.
     */
    public void setEventtype(Short value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.adventureevents.eventtype</code>.
     */
    public Short getEventtype() {
        return (Short) get(1);
    }

    /**
     * Setter for <code>public.adventureevents.creationtimestamp</code>.
     */
    public void setCreationtimestamp(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.adventureevents.creationtimestamp</code>.
     */
    public OffsetDateTime getCreationtimestamp() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.adventureevents.userid</code>.
     */
    public void setUserid(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.adventureevents.userid</code>.
     */
    public UUID getUserid() {
        return (UUID) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdventureeventsRecord
     */
    public AdventureeventsRecord() {
        super(Adventureevents.ADVENTUREEVENTS);
    }

    /**
     * Create a detached, initialised AdventureeventsRecord
     */
    public AdventureeventsRecord(UUID id, Short eventtype, OffsetDateTime creationtimestamp, UUID userid) {
        super(Adventureevents.ADVENTUREEVENTS);

        setId(id);
        setEventtype(eventtype);
        setCreationtimestamp(creationtimestamp);
        setUserid(userid);
        resetChangedOnNotNull();
    }
}
