/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.data_model.db_generated.tables.Lkarmor;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LkarmorRecord extends UpdatableRecordImpl<LkarmorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lkarmor.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lkarmor.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.lkarmor.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lkarmor.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lkarmor.exposition</code>.
     */
    public void setExposition(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lkarmor.exposition</code>.
     */
    public String getExposition() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lkarmor.cost</code>.
     */
    public void setCost(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lkarmor.cost</code>.
     */
    public Integer getCost() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.lkarmor.effecttypes</code>.
     */
    public void setEffecttypes(Short[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lkarmor.effecttypes</code>.
     */
    public Short[] getEffecttypes() {
        return (Short[]) get(4);
    }

    /**
     * Setter for <code>public.lkarmor.imageuri</code>.
     */
    public void setImageuri(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lkarmor.imageuri</code>.
     */
    public String getImageuri() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.lkarmor.defensebonus</code>.
     */
    public void setDefensebonus(Short value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lkarmor.defensebonus</code>.
     */
    public Short getDefensebonus() {
        return (Short) get(6);
    }

    /**
     * Setter for <code>public.lkarmor.evadebonus</code>.
     */
    public void setEvadebonus(Short value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.lkarmor.evadebonus</code>.
     */
    public Short getEvadebonus() {
        return (Short) get(7);
    }

    /**
     * Setter for <code>public.lkarmor.hpbonus</code>.
     */
    public void setHpbonus(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.lkarmor.hpbonus</code>.
     */
    public Short getHpbonus() {
        return (Short) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LkarmorRecord
     */
    public LkarmorRecord() {
        super(Lkarmor.LKARMOR);
    }

    /**
     * Create a detached, initialised LkarmorRecord
     */
    public LkarmorRecord(Long id, String title, String exposition, Integer cost, Short[] effecttypes, String imageuri, Short defensebonus, Short evadebonus, Short hpbonus) {
        super(Lkarmor.LKARMOR);

        setId(id);
        setTitle(title);
        setExposition(exposition);
        setCost(cost);
        setEffecttypes(effecttypes);
        setImageuri(imageuri);
        setDefensebonus(defensebonus);
        setEvadebonus(evadebonus);
        setHpbonus(hpbonus);
        resetChangedOnNotNull();
    }
}
