/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.data_model.db_generated.tables.Lkitems;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LkitemsRecord extends UpdatableRecordImpl<LkitemsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lkitems.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lkitems.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.lkitems.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lkitems.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lkitems.exposition</code>.
     */
    public void setExposition(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lkitems.exposition</code>.
     */
    public String getExposition() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lkitems.cost</code>.
     */
    public void setCost(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lkitems.cost</code>.
     */
    public Integer getCost() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.lkitems.effecttypes</code>.
     */
    public void setEffecttypes(Short[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lkitems.effecttypes</code>.
     */
    public Short[] getEffecttypes() {
        return (Short[]) get(4);
    }

    /**
     * Setter for <code>public.lkitems.imageuri</code>.
     */
    public void setImageuri(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lkitems.imageuri</code>.
     */
    public String getImageuri() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LkitemsRecord
     */
    public LkitemsRecord() {
        super(Lkitems.LKITEMS);
    }

    /**
     * Create a detached, initialised LkitemsRecord
     */
    public LkitemsRecord(Long id, String title, String exposition, Integer cost, Short[] effecttypes, String imageuri) {
        super(Lkitems.LKITEMS);

        setId(id);
        setTitle(title);
        setExposition(exposition);
        setCost(cost);
        setEffecttypes(effecttypes);
        setImageuri(imageuri);
        resetChangedOnNotNull();
    }
}
