/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.data_model.db_generated.tables.Lkusables;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class LkusablesRecord extends UpdatableRecordImpl<LkusablesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.lkusables.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.lkusables.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.lkusables.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.lkusables.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.lkusables.exposition</code>.
     */
    public void setExposition(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.lkusables.exposition</code>.
     */
    public String getExposition() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.lkusables.cost</code>.
     */
    public void setCost(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.lkusables.cost</code>.
     */
    public Integer getCost() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.lkusables.effecttypes</code>.
     */
    public void setEffecttypes(Short[] value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.lkusables.effecttypes</code>.
     */
    public Short[] getEffecttypes() {
        return (Short[]) get(4);
    }

    /**
     * Setter for <code>public.lkusables.imageuri</code>.
     */
    public void setImageuri(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.lkusables.imageuri</code>.
     */
    public String getImageuri() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.lkusables.hprestore</code>.
     */
    public void setHprestore(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.lkusables.hprestore</code>.
     */
    public Long getHprestore() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>public.lkusables.xpbonus</code>.
     */
    public void setXpbonus(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.lkusables.xpbonus</code>.
     */
    public Long getXpbonus() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>public.lkusables.goldbonus</code>.
     */
    public void setGoldbonus(Short value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.lkusables.goldbonus</code>.
     */
    public Short getGoldbonus() {
        return (Short) get(8);
    }

    /**
     * Setter for <code>public.lkusables.damagebonus</code>.
     */
    public void setDamagebonus(Short value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.lkusables.damagebonus</code>.
     */
    public Short getDamagebonus() {
        return (Short) get(9);
    }

    /**
     * Setter for <code>public.lkusables.successrate</code>.
     */
    public void setSuccessrate(Float value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.lkusables.successrate</code>.
     */
    public Float getSuccessrate() {
        return (Float) get(10);
    }

    /**
     * Setter for <code>public.lkusables.skips</code>.
     */
    public void setSkips(Short value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.lkusables.skips</code>.
     */
    public Short getSkips() {
        return (Short) get(11);
    }

    /**
     * Setter for <code>public.lkusables.saves</code>.
     */
    public void setSaves(Short value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.lkusables.saves</code>.
     */
    public Short getSaves() {
        return (Short) get(12);
    }

    /**
     * Setter for <code>public.lkusables.duration</code>.
     */
    public void setDuration(Short value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.lkusables.duration</code>.
     */
    public Short getDuration() {
        return (Short) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LkusablesRecord
     */
    public LkusablesRecord() {
        super(Lkusables.LKUSABLES);
    }

    /**
     * Create a detached, initialised LkusablesRecord
     */
    public LkusablesRecord(Long id, String title, String exposition, Integer cost, Short[] effecttypes, String imageuri, Long hprestore, Long xpbonus, Short goldbonus, Short damagebonus, Float successrate, Short skips, Short saves, Short duration) {
        super(Lkusables.LKUSABLES);

        setId(id);
        setTitle(title);
        setExposition(exposition);
        setCost(cost);
        setEffecttypes(effecttypes);
        setImageuri(imageuri);
        setHprestore(hprestore);
        setXpbonus(xpbonus);
        setGoldbonus(goldbonus);
        setDamagebonus(damagebonus);
        setSuccessrate(successrate);
        setSkips(skips);
        setSaves(saves);
        setDuration(duration);
        resetChangedOnNotNull();
    }
}
