/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables.records;


import org.jooq.impl.TableRecordImpl;

import space_habit_frontier.data_model.db_generated.tables.Monsteritemdrops;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MonsteritemdropsRecord extends TableRecordImpl<MonsteritemdropsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.monsteritemdrops.lkmonsterid</code>.
     */
    public void setLkmonsterid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.monsteritemdrops.lkmonsterid</code>.
     */
    public Long getLkmonsterid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.monsteritemdrops.lkitemid</code>.
     */
    public void setLkitemid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.monsteritemdrops.lkitemid</code>.
     */
    public Long getLkitemid() {
        return (Long) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MonsteritemdropsRecord
     */
    public MonsteritemdropsRecord() {
        super(Monsteritemdrops.MONSTERITEMDROPS);
    }

    /**
     * Create a detached, initialised MonsteritemdropsRecord
     */
    public MonsteritemdropsRecord(Long lkmonsterid, Long lkitemid) {
        super(Monsteritemdrops.MONSTERITEMDROPS);

        setLkmonsterid(lkmonsterid);
        setLkitemid(lkitemid);
        resetChangedOnNotNull();
    }
}
