/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import space_habit_frontier.data_model.db_generated.tables.Todoevents;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TodoeventsRecord extends UpdatableRecordImpl<TodoeventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.todoevents.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.todoevents.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.todoevents.damage</code>.
     */
    public void setDamage(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.todoevents.damage</code>.
     */
    public Integer getDamage() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.todoevents.creationtimestamp</code>.
     */
    public void setCreationtimestamp(OffsetDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.todoevents.creationtimestamp</code>.
     */
    public OffsetDateTime getCreationtimestamp() {
        return (OffsetDateTime) get(2);
    }

    /**
     * Setter for <code>public.todoevents.todoid</code>.
     */
    public void setTodoid(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.todoevents.todoid</code>.
     */
    public UUID getTodoid() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>public.todoevents.userid</code>.
     */
    public void setUserid(UUID value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.todoevents.userid</code>.
     */
    public UUID getUserid() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TodoeventsRecord
     */
    public TodoeventsRecord() {
        super(Todoevents.TODOEVENTS);
    }

    /**
     * Create a detached, initialised TodoeventsRecord
     */
    public TodoeventsRecord(UUID id, Integer damage, OffsetDateTime creationtimestamp, UUID todoid, UUID userid) {
        super(Todoevents.TODOEVENTS);

        setId(id);
        setDamage(damage);
        setCreationtimestamp(creationtimestamp);
        setTodoid(todoid);
        setUserid(userid);
        resetChangedOnNotNull();
    }
}
