

CREATE TABLE IF NOT EXISTS users (
	id UUID PRIMARY KEY,
	username TEXT UNIQUE NOT NULL,
	email TEXT UNIQUE NOT NULL,
	hashedpw BYTEA NOT NULL,
	conditioncode INTEGER NOT NULL DEFAULT 0,
	creationtimestamp NUMERIC(16, 4),
	daystart SMALLINT NOT NULL DEFAULT 6,
	deathgoldpenalty INTEGER NOT NULL DEFAULT 0,
	deathlvlpenalty INTEGER NOT NULL DEFAULT 0,
	adventuremode INTEGER NOT NULL DEFAULT 0
);


CREATE TABLE IF NOT EXISTS vistors (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	contents TEXT NOT NULL,
	ualength SMALLINT NOT NULL,
	uahash BYTEA NOT NULL,
	ipv4address TEXT NULL,
	ipv6address TEXT NULL
);


CREATE TABLE IF NOT EXISTS todos (
	id UUID PRIMARY KEY,
	title TEXT NOT NULL,
	note TEXT NOT NULL DEFAULT '',
	risk SMALLINT NOT NULL DEFAULT 50,
	duedatetimestamp NUMERIC(16, 4) NULL,
	effectivedatetimestamp NUMERIC(16, 4) NULL,
	streakstarttimestamp NUMERIC(16, 4) NOT NULL,
	repeatcount SMALLINT NOT NULL DEFAULT 1,
	repeattype SMALLINT NOT NULL DEFAULT 0,
	repeatrate SMALLINT NOT NULL DEFAULT 1,
	weekactivedays BIT(7) NOT NULL DEFAULT B'1111111',
	yearactivedays INTEGER[366] NOT NULL DEFAULT ARRAY[]::INTEGER[],
	creationtimestamp NUMERIC(16, 4) NOT NULL,
	userid UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
	parenttodoid UUID NULL REFERENCES todos (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS actions (
	id UUID PRIMARY KEY,
	title TEXT NOT NULL,
	note TEXT NOT NULL DEFAULT '',
	risk SMALLINT NOT NULL DEFAULT 50,
	freeviolations SMALLINT NOT NULL DEFAULT 0,
	orientationtype SMALLINT NOT NULL DEFAULT 1,
	maxcount SMALLINT NOT NULL DEFAULT -1,
	userid UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS adventureevents (
	id UUID PRIMARY KEY,
	eventtype SMALLINT NOT NULL,
	creationtimestamp NUMERIC(16, 4) NOT NULL,
	userid UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS todoevents (
	id UUID PRIMARY KEY,
	damage INT NOT NULL DEFAULT 0,
	creationtimestamp NUMERIC(16, 4) NOT NULL,
	todoid UUID REFERENCES todos (id) ON DELETE CASCADE,
	userid UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS actionevents (
	id UUID PRIMARY KEY,
	damage INT NOT NULL DEFAULT 0,
	creationtimestamp NUMERIC(16, 4) NOT NULL,
	actionid UUID REFERENCES actions (id) ON DELETE CASCADE,
	userid UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS lkdungeons (
	id BIGINT PRIMARY KEY,
	title TEXT NOT NULL,
	exposition TEXT NOT NULL,
	minlvl SMALLINT NOT NULL DEFAULT 0,
	imageuri TEXT NULL
);


CREATE TABLE IF NOT EXISTS lkmonsters (
	id BIGINT PRIMARY KEY,
	title TEXT NOT NULL,
	exposition TEXT NOT NULL,
	lvlrange INT4RANGE NOT NULL,
	xpmultiplier SMALLINT NOT NULL DEFAULT 1,
	imageuri TEXT NULL
);


CREATE TABLE IF NOT EXISTS lkdungeonlkmonsters (
	lkdungeonid BIGINT NOT NULL REFERENCES lkdungeons (id) ON DELETE CASCADE,
	lkmonsterid BIGINT NOT NULL REFERENCES lkmonsters (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS lkitems (
	id BIGINT PRIMARY KEY,
	title TEXT NOT NULL,
	exposition TEXT NOT NULL,
	cost INTEGER NOT NULL DEFAULT 0,
	effecttypes SMALLINT[],
	imageuri TEXT NULL
);


CREATE TABLE IF NOT EXISTS lkdungeonlkitems (
	lkdungeonid BIGINT NOT NULL REFERENCES lkdungeons (id) ON DELETE CASCADE,
	lkitemid BIGINT NOT NULL REFERENCES lkitems (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS monsteritemdrops (
	lkmonsterid BIGINT NOT NULL REFERENCES lkmonsters (id) ON DELETE CASCADE,
	lkitemid BIGINT NOT NULL REFERENCES lkitems (id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS lkusables (
	id BIGINT PRIMARY KEY,
	hprestore BIGINT NOT NULL DEFAULT 0,
	xpbonus BIGINT NOT NULL DEFAULT 0,
	goldbonus SMALLINT NOT NULL DEFAULT 0,
	damagebonus SMALLINT NOT NULL DEFAULT 0,
	successrate REAL NOT NULL DEFAULT 1,
	skips SMALLINT NOT NULL DEFAULT 0,
	saves SMALLINT NOT NULL DEFAULT 0,
	duration SMALLINT NOT NULL DEFAULT 0
) INHERITS (lkitems);


CREATE TABLE IF NOT EXISTS lkweapons (
	id BIGINT PRIMARY KEY,
	damagebonus SMALLINT NOT NULL DEFAULT 0,
	absorbbonus SMALLINT NOT NULL DEFAULT 0
) INHERITS (lkitems);


CREATE TABLE IF NOT EXISTS lkarmor (
	id BIGINT PRIMARY KEY,
	defensebonus SMALLINT NOT NULL DEFAULT 0,
	evadebonus SMALLINT NOT NULL DEFAULT 0,
	hpbonus SMALLINT NOT NULL DEFAULT 0
) INHERITS (lkitems);


CREATE TABLE IF NOT EXISTS hero (
	id UUID PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
	xp BIGINT NOT NULL DEFAULT 0,
	gold BIGINT NOT NULL DEFAULT 0,
	inventory JSON DEFAULT '[]'::JSON,
	monster JSON,
	dungeon JSON,
	currenthp BIGINT NOT NULL DEFAULT 0,
	activebonustypes SMALLINT[] NOT NULL DEFAULT ARRAY[]::SMALLINT[],
	activepenaltytypes SMALLINT[] NOT NULL DEFAULT ARRAY[]::SMALLINT[],
	weaponrightid BIGINT NULL REFERENCES lkweapons (id) ON DELETE SET NULL,
	weaponleftid BIGINT NULL REFERENCES lkweapons (id) ON DELETE SET NULL,
	frontarmorid BIGINT NULL REFERENCES lkarmor (id) ON DELETE SET NULL,
	backarmorid BIGINT NULL REFERENCES lkarmor (id) ON DELETE SET NULL,
	toparmorid BIGINT NULL REFERENCES lkarmor (id) ON DELETE SET NULL,
	bottomarmorid BIGINT NULL REFERENCES lkarmor (id) ON DELETE SET NULL
);


CREATE TABLE IF NOT EXISTS dungeon (
	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	title TEXT NOT NULL,
	coordinates POINT NOT NULL,
	lvl INTEGER NOT NULL DEFAULT 1,
	lkdungeonid BIGINT NOT NULL REFERENCES lkdungeons (id) ON DELETE CASCADE,
	userid UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE
);

-- CREATE TABLE IF NOT EXISTS monsters (
-- 	id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
-- 	lkmonsterid BIGINT NOT NULL REFERENCES lkmonsters (id),
-- 	lvl SMALLINT NOT NULL,
-- 	userid BIGINT NOT NULL REFERENCES users (id),
-- );