ALTER TABLE todos 
ADD COLUMN IF NOT EXISTS monthactivedays INTEGER[31] NOT NULL DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN IF NOT EXISTS poisonous BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS expirationdatetimestamp TIMESTAMPTZ NULL,
ADD COLUMN IF NOT EXISTS rateinversionflag BOOLEAN NOT NULL DEFAULT FALSE

ALTER TABLE hero
ADD COLUMN IF NOT EXISTS touchedtimestamp TIMESTAMPTZ NOT NULL,