/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.engine.db_generated;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import space_habit_frontier.engine.db_generated.tables.Actionevents;
import space_habit_frontier.engine.db_generated.tables.Actions;
import space_habit_frontier.engine.db_generated.tables.Adventureevents;
import space_habit_frontier.engine.db_generated.tables.Dungeon;
import space_habit_frontier.engine.db_generated.tables.FlywaySchemaHistory;
import space_habit_frontier.engine.db_generated.tables.Hero;
import space_habit_frontier.engine.db_generated.tables.Lkarmor;
import space_habit_frontier.engine.db_generated.tables.Lkdungeonlkitems;
import space_habit_frontier.engine.db_generated.tables.Lkdungeonlkmonsters;
import space_habit_frontier.engine.db_generated.tables.Lkdungeons;
import space_habit_frontier.engine.db_generated.tables.Lkitems;
import space_habit_frontier.engine.db_generated.tables.Lkmonsters;
import space_habit_frontier.engine.db_generated.tables.Lkusables;
import space_habit_frontier.engine.db_generated.tables.Lkweapons;
import space_habit_frontier.engine.db_generated.tables.Monsteritemdrops;
import space_habit_frontier.engine.db_generated.tables.Todoevents;
import space_habit_frontier.engine.db_generated.tables.Todos;
import space_habit_frontier.engine.db_generated.tables.Users;
import space_habit_frontier.engine.db_generated.tables.Usersessions;
import space_habit_frontier.engine.db_generated.tables.Visitors;
import space_habit_frontier.engine.db_generated.tables.records.ActioneventsRecord;
import space_habit_frontier.engine.db_generated.tables.records.ActionsRecord;
import space_habit_frontier.engine.db_generated.tables.records.AdventureeventsRecord;
import space_habit_frontier.engine.db_generated.tables.records.DungeonRecord;
import space_habit_frontier.engine.db_generated.tables.records.FlywaySchemaHistoryRecord;
import space_habit_frontier.engine.db_generated.tables.records.HeroRecord;
import space_habit_frontier.engine.db_generated.tables.records.LkarmorRecord;
import space_habit_frontier.engine.db_generated.tables.records.LkdungeonlkitemsRecord;
import space_habit_frontier.engine.db_generated.tables.records.LkdungeonlkmonstersRecord;
import space_habit_frontier.engine.db_generated.tables.records.LkdungeonsRecord;
import space_habit_frontier.engine.db_generated.tables.records.LkitemsRecord;
import space_habit_frontier.engine.db_generated.tables.records.LkmonstersRecord;
import space_habit_frontier.engine.db_generated.tables.records.LkusablesRecord;
import space_habit_frontier.engine.db_generated.tables.records.LkweaponsRecord;
import space_habit_frontier.engine.db_generated.tables.records.MonsteritemdropsRecord;
import space_habit_frontier.engine.db_generated.tables.records.TodoeventsRecord;
import space_habit_frontier.engine.db_generated.tables.records.TodosRecord;
import space_habit_frontier.engine.db_generated.tables.records.UsersRecord;
import space_habit_frontier.engine.db_generated.tables.records.UsersessionsRecord;
import space_habit_frontier.engine.db_generated.tables.records.VisitorsRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ActioneventsRecord> ACTIONEVENTS_PKEY = Internal.createUniqueKey(Actionevents.ACTIONEVENTS, DSL.name("actionevents_pkey"), new TableField[] { Actionevents.ACTIONEVENTS.ID }, true);
    public static final UniqueKey<ActionsRecord> ACTIONS_PKEY = Internal.createUniqueKey(Actions.ACTIONS, DSL.name("actions_pkey"), new TableField[] { Actions.ACTIONS.ID }, true);
    public static final UniqueKey<AdventureeventsRecord> ADVENTUREEVENTS_PKEY = Internal.createUniqueKey(Adventureevents.ADVENTUREEVENTS, DSL.name("adventureevents_pkey"), new TableField[] { Adventureevents.ADVENTUREEVENTS.ID }, true);
    public static final UniqueKey<DungeonRecord> DUNGEON_PKEY = Internal.createUniqueKey(Dungeon.DUNGEON, DSL.name("dungeon_pkey"), new TableField[] { Dungeon.DUNGEON.ID }, true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<HeroRecord> HERO_PKEY = Internal.createUniqueKey(Hero.HERO, DSL.name("hero_pkey"), new TableField[] { Hero.HERO.ID }, true);
    public static final UniqueKey<LkarmorRecord> LKARMOR_PKEY = Internal.createUniqueKey(Lkarmor.LKARMOR, DSL.name("lkarmor_pkey"), new TableField[] { Lkarmor.LKARMOR.ID }, true);
    public static final UniqueKey<LkdungeonsRecord> LKDUNGEONS_PKEY = Internal.createUniqueKey(Lkdungeons.LKDUNGEONS, DSL.name("lkdungeons_pkey"), new TableField[] { Lkdungeons.LKDUNGEONS.ID }, true);
    public static final UniqueKey<LkitemsRecord> LKITEMS_PKEY = Internal.createUniqueKey(Lkitems.LKITEMS, DSL.name("lkitems_pkey"), new TableField[] { Lkitems.LKITEMS.ID }, true);
    public static final UniqueKey<LkmonstersRecord> LKMONSTERS_PKEY = Internal.createUniqueKey(Lkmonsters.LKMONSTERS, DSL.name("lkmonsters_pkey"), new TableField[] { Lkmonsters.LKMONSTERS.ID }, true);
    public static final UniqueKey<LkusablesRecord> LKUSABLES_PKEY = Internal.createUniqueKey(Lkusables.LKUSABLES, DSL.name("lkusables_pkey"), new TableField[] { Lkusables.LKUSABLES.ID }, true);
    public static final UniqueKey<LkweaponsRecord> LKWEAPONS_PKEY = Internal.createUniqueKey(Lkweapons.LKWEAPONS, DSL.name("lkweapons_pkey"), new TableField[] { Lkweapons.LKWEAPONS.ID }, true);
    public static final UniqueKey<TodoeventsRecord> TODOEVENTS_PKEY = Internal.createUniqueKey(Todoevents.TODOEVENTS, DSL.name("todoevents_pkey"), new TableField[] { Todoevents.TODOEVENTS.ID }, true);
    public static final UniqueKey<TodosRecord> TODOS_PKEY = Internal.createUniqueKey(Todos.TODOS, DSL.name("todos_pkey"), new TableField[] { Todos.TODOS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_email_key"), new TableField[] { Users.USERS.EMAIL }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_username_key"), new TableField[] { Users.USERS.USERNAME }, true);
    public static final UniqueKey<UsersessionsRecord> USERSESSIONS_PKEY = Internal.createUniqueKey(Usersessions.USERSESSIONS, DSL.name("usersessions_pkey"), new TableField[] { Usersessions.USERSESSIONS.ID }, true);
    public static final UniqueKey<VisitorsRecord> VISTORS_PKEY = Internal.createUniqueKey(Visitors.VISITORS, DSL.name("vistors_pkey"), new TableField[] { Visitors.VISITORS.ID }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<ActioneventsRecord, ActionsRecord> ACTIONEVENTS__ACTIONEVENTS_ACTIONID_FKEY = Internal.createForeignKey(Actionevents.ACTIONEVENTS, DSL.name("actionevents_actionid_fkey"), new TableField[] { Actionevents.ACTIONEVENTS.ACTIONID }, Keys.ACTIONS_PKEY, new TableField[] { Actions.ACTIONS.ID }, true);
    public static final ForeignKey<ActioneventsRecord, UsersRecord> ACTIONEVENTS__ACTIONEVENTS_USERID_FKEY = Internal.createForeignKey(Actionevents.ACTIONEVENTS, DSL.name("actionevents_userid_fkey"), new TableField[] { Actionevents.ACTIONEVENTS.USERID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<ActionsRecord, UsersRecord> ACTIONS__ACTIONS_USERID_FKEY = Internal.createForeignKey(Actions.ACTIONS, DSL.name("actions_userid_fkey"), new TableField[] { Actions.ACTIONS.USERID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<AdventureeventsRecord, UsersRecord> ADVENTUREEVENTS__ADVENTUREEVENTS_USERID_FKEY = Internal.createForeignKey(Adventureevents.ADVENTUREEVENTS, DSL.name("adventureevents_userid_fkey"), new TableField[] { Adventureevents.ADVENTUREEVENTS.USERID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<DungeonRecord, LkdungeonsRecord> DUNGEON__DUNGEON_LKDUNGEONID_FKEY = Internal.createForeignKey(Dungeon.DUNGEON, DSL.name("dungeon_lkdungeonid_fkey"), new TableField[] { Dungeon.DUNGEON.LKDUNGEONID }, Keys.LKDUNGEONS_PKEY, new TableField[] { Lkdungeons.LKDUNGEONS.ID }, true);
    public static final ForeignKey<DungeonRecord, UsersRecord> DUNGEON__DUNGEON_USERID_FKEY = Internal.createForeignKey(Dungeon.DUNGEON, DSL.name("dungeon_userid_fkey"), new TableField[] { Dungeon.DUNGEON.USERID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<HeroRecord, LkarmorRecord> HERO__HERO_BACKARMORID_FKEY = Internal.createForeignKey(Hero.HERO, DSL.name("hero_backarmorid_fkey"), new TableField[] { Hero.HERO.BACKARMORID }, Keys.LKARMOR_PKEY, new TableField[] { Lkarmor.LKARMOR.ID }, true);
    public static final ForeignKey<HeroRecord, LkarmorRecord> HERO__HERO_BOTTOMARMORID_FKEY = Internal.createForeignKey(Hero.HERO, DSL.name("hero_bottomarmorid_fkey"), new TableField[] { Hero.HERO.BOTTOMARMORID }, Keys.LKARMOR_PKEY, new TableField[] { Lkarmor.LKARMOR.ID }, true);
    public static final ForeignKey<HeroRecord, LkarmorRecord> HERO__HERO_FRONTARMORID_FKEY = Internal.createForeignKey(Hero.HERO, DSL.name("hero_frontarmorid_fkey"), new TableField[] { Hero.HERO.FRONTARMORID }, Keys.LKARMOR_PKEY, new TableField[] { Lkarmor.LKARMOR.ID }, true);
    public static final ForeignKey<HeroRecord, UsersRecord> HERO__HERO_ID_FKEY = Internal.createForeignKey(Hero.HERO, DSL.name("hero_id_fkey"), new TableField[] { Hero.HERO.ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<HeroRecord, LkarmorRecord> HERO__HERO_TOPARMORID_FKEY = Internal.createForeignKey(Hero.HERO, DSL.name("hero_toparmorid_fkey"), new TableField[] { Hero.HERO.TOPARMORID }, Keys.LKARMOR_PKEY, new TableField[] { Lkarmor.LKARMOR.ID }, true);
    public static final ForeignKey<HeroRecord, LkweaponsRecord> HERO__HERO_WEAPONLEFTID_FKEY = Internal.createForeignKey(Hero.HERO, DSL.name("hero_weaponleftid_fkey"), new TableField[] { Hero.HERO.WEAPONLEFTID }, Keys.LKWEAPONS_PKEY, new TableField[] { Lkweapons.LKWEAPONS.ID }, true);
    public static final ForeignKey<HeroRecord, LkweaponsRecord> HERO__HERO_WEAPONRIGHTID_FKEY = Internal.createForeignKey(Hero.HERO, DSL.name("hero_weaponrightid_fkey"), new TableField[] { Hero.HERO.WEAPONRIGHTID }, Keys.LKWEAPONS_PKEY, new TableField[] { Lkweapons.LKWEAPONS.ID }, true);
    public static final ForeignKey<LkdungeonlkitemsRecord, LkdungeonsRecord> LKDUNGEONLKITEMS__LKDUNGEONLKITEMS_LKDUNGEONID_FKEY = Internal.createForeignKey(Lkdungeonlkitems.LKDUNGEONLKITEMS, DSL.name("lkdungeonlkitems_lkdungeonid_fkey"), new TableField[] { Lkdungeonlkitems.LKDUNGEONLKITEMS.LKDUNGEONID }, Keys.LKDUNGEONS_PKEY, new TableField[] { Lkdungeons.LKDUNGEONS.ID }, true);
    public static final ForeignKey<LkdungeonlkitemsRecord, LkitemsRecord> LKDUNGEONLKITEMS__LKDUNGEONLKITEMS_LKITEMID_FKEY = Internal.createForeignKey(Lkdungeonlkitems.LKDUNGEONLKITEMS, DSL.name("lkdungeonlkitems_lkitemid_fkey"), new TableField[] { Lkdungeonlkitems.LKDUNGEONLKITEMS.LKITEMID }, Keys.LKITEMS_PKEY, new TableField[] { Lkitems.LKITEMS.ID }, true);
    public static final ForeignKey<LkdungeonlkmonstersRecord, LkdungeonsRecord> LKDUNGEONLKMONSTERS__LKDUNGEONLKMONSTERS_LKDUNGEONID_FKEY = Internal.createForeignKey(Lkdungeonlkmonsters.LKDUNGEONLKMONSTERS, DSL.name("lkdungeonlkmonsters_lkdungeonid_fkey"), new TableField[] { Lkdungeonlkmonsters.LKDUNGEONLKMONSTERS.LKDUNGEONID }, Keys.LKDUNGEONS_PKEY, new TableField[] { Lkdungeons.LKDUNGEONS.ID }, true);
    public static final ForeignKey<LkdungeonlkmonstersRecord, LkmonstersRecord> LKDUNGEONLKMONSTERS__LKDUNGEONLKMONSTERS_LKMONSTERID_FKEY = Internal.createForeignKey(Lkdungeonlkmonsters.LKDUNGEONLKMONSTERS, DSL.name("lkdungeonlkmonsters_lkmonsterid_fkey"), new TableField[] { Lkdungeonlkmonsters.LKDUNGEONLKMONSTERS.LKMONSTERID }, Keys.LKMONSTERS_PKEY, new TableField[] { Lkmonsters.LKMONSTERS.ID }, true);
    public static final ForeignKey<MonsteritemdropsRecord, LkitemsRecord> MONSTERITEMDROPS__MONSTERITEMDROPS_LKITEMID_FKEY = Internal.createForeignKey(Monsteritemdrops.MONSTERITEMDROPS, DSL.name("monsteritemdrops_lkitemid_fkey"), new TableField[] { Monsteritemdrops.MONSTERITEMDROPS.LKITEMID }, Keys.LKITEMS_PKEY, new TableField[] { Lkitems.LKITEMS.ID }, true);
    public static final ForeignKey<MonsteritemdropsRecord, LkmonstersRecord> MONSTERITEMDROPS__MONSTERITEMDROPS_LKMONSTERID_FKEY = Internal.createForeignKey(Monsteritemdrops.MONSTERITEMDROPS, DSL.name("monsteritemdrops_lkmonsterid_fkey"), new TableField[] { Monsteritemdrops.MONSTERITEMDROPS.LKMONSTERID }, Keys.LKMONSTERS_PKEY, new TableField[] { Lkmonsters.LKMONSTERS.ID }, true);
    public static final ForeignKey<TodoeventsRecord, TodosRecord> TODOEVENTS__TODOEVENTS_TODOID_FKEY = Internal.createForeignKey(Todoevents.TODOEVENTS, DSL.name("todoevents_todoid_fkey"), new TableField[] { Todoevents.TODOEVENTS.TODOID }, Keys.TODOS_PKEY, new TableField[] { Todos.TODOS.ID }, true);
    public static final ForeignKey<TodoeventsRecord, UsersRecord> TODOEVENTS__TODOEVENTS_USERID_FKEY = Internal.createForeignKey(Todoevents.TODOEVENTS, DSL.name("todoevents_userid_fkey"), new TableField[] { Todoevents.TODOEVENTS.USERID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<TodosRecord, TodosRecord> TODOS__TODOS_PARENTTODOID_FKEY = Internal.createForeignKey(Todos.TODOS, DSL.name("todos_parenttodoid_fkey"), new TableField[] { Todos.TODOS.PARENTTODOID }, Keys.TODOS_PKEY, new TableField[] { Todos.TODOS.ID }, true);
    public static final ForeignKey<TodosRecord, UsersRecord> TODOS__TODOS_USERID_FKEY = Internal.createForeignKey(Todos.TODOS, DSL.name("todos_userid_fkey"), new TableField[] { Todos.TODOS.USERID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<UsersessionsRecord, UsersRecord> USERSESSIONS__USERSESSIONS_USERID_FKEY = Internal.createForeignKey(Usersessions.USERSESSIONS, DSL.name("usersessions_userid_fkey"), new TableField[] { Usersessions.USERSESSIONS.USERID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true);
    public static final ForeignKey<UsersessionsRecord, VisitorsRecord> USERSESSIONS__USERSESSIONS_VISITORID_FKEY = Internal.createForeignKey(Usersessions.USERSESSIONS, DSL.name("usersessions_visitorid_fkey"), new TableField[] { Usersessions.USERSESSIONS.VISITORID }, Keys.VISTORS_PKEY, new TableField[] { Visitors.VISITORS.ID }, true);
}
