/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.data_model.db_generated.Keys;
import space_habit_frontier.data_model.db_generated.Public;
import space_habit_frontier.data_model.db_generated.tables.Actions.ActionsPath;
import space_habit_frontier.data_model.db_generated.tables.Users.UsersPath;
import space_habit_frontier.data_model.db_generated.tables.records.ActioneventsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Actionevents extends TableImpl<ActioneventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.actionevents</code>
     */
    public static final Actionevents ACTIONEVENTS = new Actionevents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActioneventsRecord> getRecordType() {
        return ActioneventsRecord.class;
    }

    /**
     * The column <code>public.actionevents.id</code>.
     */
    public final TableField<ActioneventsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.actionevents.damage</code>.
     */
    public final TableField<ActioneventsRecord, Integer> DAMAGE = createField(DSL.name("damage"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.actionevents.creationtimestamp</code>.
     */
    public final TableField<ActioneventsRecord, OffsetDateTime> CREATIONTIMESTAMP = createField(DSL.name("creationtimestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.actionevents.actionid</code>.
     */
    public final TableField<ActioneventsRecord, UUID> ACTIONID = createField(DSL.name("actionid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.actionevents.userid</code>.
     */
    public final TableField<ActioneventsRecord, UUID> USERID = createField(DSL.name("userid"), SQLDataType.UUID.nullable(false), this, "");

    private Actionevents(Name alias, Table<ActioneventsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Actionevents(Name alias, Table<ActioneventsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.actionevents</code> table reference
     */
    public Actionevents(String alias) {
        this(DSL.name(alias), ACTIONEVENTS);
    }

    /**
     * Create an aliased <code>public.actionevents</code> table reference
     */
    public Actionevents(Name alias) {
        this(alias, ACTIONEVENTS);
    }

    /**
     * Create a <code>public.actionevents</code> table reference
     */
    public Actionevents() {
        this(DSL.name("actionevents"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ActioneventsRecord> getPrimaryKey() {
        return Keys.ACTIONEVENTS_PKEY;
    }

    @Override
    public List<ForeignKey<ActioneventsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ACTIONEVENTS__ACTIONEVENTS_ACTIONID_FKEY, Keys.ACTIONEVENTS__ACTIONEVENTS_USERID_FKEY);
    }

    private transient ActionsPath _actions;

    /**
     * Get the implicit join path to the <code>public.actions</code> table.
     */
    public ActionsPath actions() {
        if (_actions == null)
            _actions = new ActionsPath(this, Keys.ACTIONEVENTS__ACTIONEVENTS_ACTIONID_FKEY, null);

        return _actions;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.ACTIONEVENTS__ACTIONEVENTS_USERID_FKEY, null);

        return _users;
    }

    @Override
    public Actionevents as(String alias) {
        return new Actionevents(DSL.name(alias), this);
    }

    @Override
    public Actionevents as(Name alias) {
        return new Actionevents(alias, this);
    }

    @Override
    public Actionevents as(Table<?> alias) {
        return new Actionevents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Actionevents rename(String name) {
        return new Actionevents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Actionevents rename(Name name) {
        return new Actionevents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Actionevents rename(Table<?> name) {
        return new Actionevents(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actionevents where(Condition condition) {
        return new Actionevents(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actionevents where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actionevents where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actionevents where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Actionevents where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Actionevents where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Actionevents where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Actionevents where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actionevents whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actionevents whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
