/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.data_model.db_generated.Keys;
import space_habit_frontier.data_model.db_generated.Public;
import space_habit_frontier.data_model.db_generated.tables.Users.UsersPath;
import space_habit_frontier.data_model.db_generated.tables.records.ActionsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Actions extends TableImpl<ActionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.actions</code>
     */
    public static final Actions ACTIONS = new Actions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ActionsRecord> getRecordType() {
        return ActionsRecord.class;
    }

    /**
     * The column <code>public.actions.id</code>.
     */
    public final TableField<ActionsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.actions.title</code>.
     */
    public final TableField<ActionsRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.actions.note</code>.
     */
    public final TableField<ActionsRecord, String> NOTE = createField(DSL.name("note"), SQLDataType.CLOB.nullable(false).defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)), this, "");

    /**
     * The column <code>public.actions.risk</code>.
     */
    public final TableField<ActionsRecord, Short> RISK = createField(DSL.name("risk"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("50"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.actions.freeviolations</code>.
     */
    public final TableField<ActionsRecord, Short> FREEVIOLATIONS = createField(DSL.name("freeviolations"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.actions.orientationtype</code>.
     */
    public final TableField<ActionsRecord, Short> ORIENTATIONTYPE = createField(DSL.name("orientationtype"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.actions.maxcount</code>.
     */
    public final TableField<ActionsRecord, Short> MAXCOUNT = createField(DSL.name("maxcount"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("'-1'::integer"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.actions.userid</code>.
     */
    public final TableField<ActionsRecord, UUID> USERID = createField(DSL.name("userid"), SQLDataType.UUID.nullable(false), this, "");

    private Actions(Name alias, Table<ActionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Actions(Name alias, Table<ActionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.actions</code> table reference
     */
    public Actions(String alias) {
        this(DSL.name(alias), ACTIONS);
    }

    /**
     * Create an aliased <code>public.actions</code> table reference
     */
    public Actions(Name alias) {
        this(alias, ACTIONS);
    }

    /**
     * Create a <code>public.actions</code> table reference
     */
    public Actions() {
        this(DSL.name("actions"), null);
    }

    public <O extends Record> Actions(Table<O> path, ForeignKey<O, ActionsRecord> childPath, InverseForeignKey<O, ActionsRecord> parentPath) {
        super(path, childPath, parentPath, ACTIONS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ActionsPath extends Actions implements Path<ActionsRecord> {
        public <O extends Record> ActionsPath(Table<O> path, ForeignKey<O, ActionsRecord> childPath, InverseForeignKey<O, ActionsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ActionsPath(Name alias, Table<ActionsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ActionsPath as(String alias) {
            return new ActionsPath(DSL.name(alias), this);
        }

        @Override
        public ActionsPath as(Name alias) {
            return new ActionsPath(alias, this);
        }

        @Override
        public ActionsPath as(Table<?> alias) {
            return new ActionsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ActionsRecord> getPrimaryKey() {
        return Keys.ACTIONS_PKEY;
    }

    @Override
    public List<ForeignKey<ActionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ACTIONS__ACTIONS_USERID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.ACTIONS__ACTIONS_USERID_FKEY, null);

        return _users;
    }

    @Override
    public Actions as(String alias) {
        return new Actions(DSL.name(alias), this);
    }

    @Override
    public Actions as(Name alias) {
        return new Actions(alias, this);
    }

    @Override
    public Actions as(Table<?> alias) {
        return new Actions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Actions rename(String name) {
        return new Actions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Actions rename(Name name) {
        return new Actions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Actions rename(Table<?> name) {
        return new Actions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actions where(Condition condition) {
        return new Actions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Actions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Actions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Actions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Actions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Actions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
