/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSON;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.data_model.db_generated.Keys;
import space_habit_frontier.data_model.db_generated.Public;
import space_habit_frontier.data_model.db_generated.tables.Lkarmor.LkarmorPath;
import space_habit_frontier.data_model.db_generated.tables.Lkweapons.LkweaponsPath;
import space_habit_frontier.data_model.db_generated.tables.Users.UsersPath;
import space_habit_frontier.data_model.db_generated.tables.records.HeroRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Hero extends TableImpl<HeroRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.hero</code>
     */
    public static final Hero HERO = new Hero();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HeroRecord> getRecordType() {
        return HeroRecord.class;
    }

    /**
     * The column <code>public.hero.id</code>.
     */
    public final TableField<HeroRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.hero.xp</code>.
     */
    public final TableField<HeroRecord, Long> XP = createField(DSL.name("xp"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.hero.gold</code>.
     */
    public final TableField<HeroRecord, Long> GOLD = createField(DSL.name("gold"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.hero.inventory</code>.
     */
    public final TableField<HeroRecord, JSON> INVENTORY = createField(DSL.name("inventory"), SQLDataType.JSON.defaultValue(DSL.field(DSL.raw("'[]'::json"), SQLDataType.JSON)), this, "");

    /**
     * The column <code>public.hero.monster</code>.
     */
    public final TableField<HeroRecord, JSON> MONSTER = createField(DSL.name("monster"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.hero.dungeon</code>.
     */
    public final TableField<HeroRecord, JSON> DUNGEON = createField(DSL.name("dungeon"), SQLDataType.JSON, this, "");

    /**
     * The column <code>public.hero.currenthp</code>.
     */
    public final TableField<HeroRecord, Long> CURRENTHP = createField(DSL.name("currenthp"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.hero.activebonustypes</code>.
     */
    public final TableField<HeroRecord, Short[]> ACTIVEBONUSTYPES = createField(DSL.name("activebonustypes"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY[]::smallint[]"), SQLDataType.SMALLINT)).array(), this, "");

    /**
     * The column <code>public.hero.activepenaltytypes</code>.
     */
    public final TableField<HeroRecord, Short[]> ACTIVEPENALTYTYPES = createField(DSL.name("activepenaltytypes"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("ARRAY[]::smallint[]"), SQLDataType.SMALLINT)).array(), this, "");

    /**
     * The column <code>public.hero.weaponrightid</code>.
     */
    public final TableField<HeroRecord, Long> WEAPONRIGHTID = createField(DSL.name("weaponrightid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.hero.weaponleftid</code>.
     */
    public final TableField<HeroRecord, Long> WEAPONLEFTID = createField(DSL.name("weaponleftid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.hero.frontarmorid</code>.
     */
    public final TableField<HeroRecord, Long> FRONTARMORID = createField(DSL.name("frontarmorid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.hero.backarmorid</code>.
     */
    public final TableField<HeroRecord, Long> BACKARMORID = createField(DSL.name("backarmorid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.hero.toparmorid</code>.
     */
    public final TableField<HeroRecord, Long> TOPARMORID = createField(DSL.name("toparmorid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.hero.bottomarmorid</code>.
     */
    public final TableField<HeroRecord, Long> BOTTOMARMORID = createField(DSL.name("bottomarmorid"), SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.hero.touchedtimestamp</code>.
     */
    public final TableField<HeroRecord, OffsetDateTime> TOUCHEDTIMESTAMP = createField(DSL.name("touchedtimestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    private Hero(Name alias, Table<HeroRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Hero(Name alias, Table<HeroRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.hero</code> table reference
     */
    public Hero(String alias) {
        this(DSL.name(alias), HERO);
    }

    /**
     * Create an aliased <code>public.hero</code> table reference
     */
    public Hero(Name alias) {
        this(alias, HERO);
    }

    /**
     * Create a <code>public.hero</code> table reference
     */
    public Hero() {
        this(DSL.name("hero"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<HeroRecord> getPrimaryKey() {
        return Keys.HERO_PKEY;
    }

    @Override
    public List<ForeignKey<HeroRecord, ?>> getReferences() {
        return Arrays.asList(Keys.HERO__HERO_ID_FKEY, Keys.HERO__HERO_WEAPONRIGHTID_FKEY, Keys.HERO__HERO_WEAPONLEFTID_FKEY, Keys.HERO__HERO_FRONTARMORID_FKEY, Keys.HERO__HERO_BACKARMORID_FKEY, Keys.HERO__HERO_TOPARMORID_FKEY, Keys.HERO__HERO_BOTTOMARMORID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.HERO__HERO_ID_FKEY, null);

        return _users;
    }

    private transient LkweaponsPath _heroWeaponrightidFkey;

    /**
     * Get the implicit join path to the <code>public.lkweapons</code> table,
     * via the <code>hero_weaponrightid_fkey</code> key.
     */
    public LkweaponsPath heroWeaponrightidFkey() {
        if (_heroWeaponrightidFkey == null)
            _heroWeaponrightidFkey = new LkweaponsPath(this, Keys.HERO__HERO_WEAPONRIGHTID_FKEY, null);

        return _heroWeaponrightidFkey;
    }

    private transient LkweaponsPath _heroWeaponleftidFkey;

    /**
     * Get the implicit join path to the <code>public.lkweapons</code> table,
     * via the <code>hero_weaponleftid_fkey</code> key.
     */
    public LkweaponsPath heroWeaponleftidFkey() {
        if (_heroWeaponleftidFkey == null)
            _heroWeaponleftidFkey = new LkweaponsPath(this, Keys.HERO__HERO_WEAPONLEFTID_FKEY, null);

        return _heroWeaponleftidFkey;
    }

    private transient LkarmorPath _heroFrontarmoridFkey;

    /**
     * Get the implicit join path to the <code>public.lkarmor</code> table, via
     * the <code>hero_frontarmorid_fkey</code> key.
     */
    public LkarmorPath heroFrontarmoridFkey() {
        if (_heroFrontarmoridFkey == null)
            _heroFrontarmoridFkey = new LkarmorPath(this, Keys.HERO__HERO_FRONTARMORID_FKEY, null);

        return _heroFrontarmoridFkey;
    }

    private transient LkarmorPath _heroBackarmoridFkey;

    /**
     * Get the implicit join path to the <code>public.lkarmor</code> table, via
     * the <code>hero_backarmorid_fkey</code> key.
     */
    public LkarmorPath heroBackarmoridFkey() {
        if (_heroBackarmoridFkey == null)
            _heroBackarmoridFkey = new LkarmorPath(this, Keys.HERO__HERO_BACKARMORID_FKEY, null);

        return _heroBackarmoridFkey;
    }

    private transient LkarmorPath _heroToparmoridFkey;

    /**
     * Get the implicit join path to the <code>public.lkarmor</code> table, via
     * the <code>hero_toparmorid_fkey</code> key.
     */
    public LkarmorPath heroToparmoridFkey() {
        if (_heroToparmoridFkey == null)
            _heroToparmoridFkey = new LkarmorPath(this, Keys.HERO__HERO_TOPARMORID_FKEY, null);

        return _heroToparmoridFkey;
    }

    private transient LkarmorPath _heroBottomarmoridFkey;

    /**
     * Get the implicit join path to the <code>public.lkarmor</code> table, via
     * the <code>hero_bottomarmorid_fkey</code> key.
     */
    public LkarmorPath heroBottomarmoridFkey() {
        if (_heroBottomarmoridFkey == null)
            _heroBottomarmoridFkey = new LkarmorPath(this, Keys.HERO__HERO_BOTTOMARMORID_FKEY, null);

        return _heroBottomarmoridFkey;
    }

    @Override
    public Hero as(String alias) {
        return new Hero(DSL.name(alias), this);
    }

    @Override
    public Hero as(Name alias) {
        return new Hero(alias, this);
    }

    @Override
    public Hero as(Table<?> alias) {
        return new Hero(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Hero rename(String name) {
        return new Hero(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hero rename(Name name) {
        return new Hero(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Hero rename(Table<?> name) {
        return new Hero(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hero where(Condition condition) {
        return new Hero(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hero where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hero where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hero where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hero where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hero where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hero where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Hero where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hero whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Hero whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
