/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.data_model.db_generated.Keys;
import space_habit_frontier.data_model.db_generated.Public;
import space_habit_frontier.data_model.db_generated.tables.records.LkarmorRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lkarmor extends TableImpl<LkarmorRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.lkarmor</code>
     */
    public static final Lkarmor LKARMOR = new Lkarmor();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LkarmorRecord> getRecordType() {
        return LkarmorRecord.class;
    }

    /**
     * The column <code>public.lkarmor.id</code>.
     */
    public final TableField<LkarmorRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.lkarmor.title</code>.
     */
    public final TableField<LkarmorRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.lkarmor.exposition</code>.
     */
    public final TableField<LkarmorRecord, String> EXPOSITION = createField(DSL.name("exposition"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.lkarmor.cost</code>.
     */
    public final TableField<LkarmorRecord, Integer> COST = createField(DSL.name("cost"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.lkarmor.effecttypes</code>.
     */
    public final TableField<LkarmorRecord, Short[]> EFFECTTYPES = createField(DSL.name("effecttypes"), SQLDataType.SMALLINT.array(), this, "");

    /**
     * The column <code>public.lkarmor.imageuri</code>.
     */
    public final TableField<LkarmorRecord, String> IMAGEURI = createField(DSL.name("imageuri"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.lkarmor.defensebonus</code>.
     */
    public final TableField<LkarmorRecord, Short> DEFENSEBONUS = createField(DSL.name("defensebonus"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.lkarmor.evadebonus</code>.
     */
    public final TableField<LkarmorRecord, Short> EVADEBONUS = createField(DSL.name("evadebonus"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.lkarmor.hpbonus</code>.
     */
    public final TableField<LkarmorRecord, Short> HPBONUS = createField(DSL.name("hpbonus"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    private Lkarmor(Name alias, Table<LkarmorRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lkarmor(Name alias, Table<LkarmorRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.lkarmor</code> table reference
     */
    public Lkarmor(String alias) {
        this(DSL.name(alias), LKARMOR);
    }

    /**
     * Create an aliased <code>public.lkarmor</code> table reference
     */
    public Lkarmor(Name alias) {
        this(alias, LKARMOR);
    }

    /**
     * Create a <code>public.lkarmor</code> table reference
     */
    public Lkarmor() {
        this(DSL.name("lkarmor"), null);
    }

    public <O extends Record> Lkarmor(Table<O> path, ForeignKey<O, LkarmorRecord> childPath, InverseForeignKey<O, LkarmorRecord> parentPath) {
        super(path, childPath, parentPath, LKARMOR);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LkarmorPath extends Lkarmor implements Path<LkarmorRecord> {
        public <O extends Record> LkarmorPath(Table<O> path, ForeignKey<O, LkarmorRecord> childPath, InverseForeignKey<O, LkarmorRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LkarmorPath(Name alias, Table<LkarmorRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LkarmorPath as(String alias) {
            return new LkarmorPath(DSL.name(alias), this);
        }

        @Override
        public LkarmorPath as(Name alias) {
            return new LkarmorPath(alias, this);
        }

        @Override
        public LkarmorPath as(Table<?> alias) {
            return new LkarmorPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<LkarmorRecord> getPrimaryKey() {
        return Keys.LKARMOR_PKEY;
    }

    @Override
    public Lkarmor as(String alias) {
        return new Lkarmor(DSL.name(alias), this);
    }

    @Override
    public Lkarmor as(Name alias) {
        return new Lkarmor(alias, this);
    }

    @Override
    public Lkarmor as(Table<?> alias) {
        return new Lkarmor(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkarmor rename(String name) {
        return new Lkarmor(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkarmor rename(Name name) {
        return new Lkarmor(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkarmor rename(Table<?> name) {
        return new Lkarmor(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkarmor where(Condition condition) {
        return new Lkarmor(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkarmor where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkarmor where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkarmor where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkarmor where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkarmor where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkarmor where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkarmor where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkarmor whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkarmor whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
