/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.data_model.db_generated.Keys;
import space_habit_frontier.data_model.db_generated.Public;
import space_habit_frontier.data_model.db_generated.tables.Lkdungeons.LkdungeonsPath;
import space_habit_frontier.data_model.db_generated.tables.Lkmonsters.LkmonstersPath;
import space_habit_frontier.data_model.db_generated.tables.records.LkdungeonlkmonstersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lkdungeonlkmonsters extends TableImpl<LkdungeonlkmonstersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.lkdungeonlkmonsters</code>
     */
    public static final Lkdungeonlkmonsters LKDUNGEONLKMONSTERS = new Lkdungeonlkmonsters();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LkdungeonlkmonstersRecord> getRecordType() {
        return LkdungeonlkmonstersRecord.class;
    }

    /**
     * The column <code>public.lkdungeonlkmonsters.lkdungeonid</code>.
     */
    public final TableField<LkdungeonlkmonstersRecord, Long> LKDUNGEONID = createField(DSL.name("lkdungeonid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.lkdungeonlkmonsters.lkmonsterid</code>.
     */
    public final TableField<LkdungeonlkmonstersRecord, Long> LKMONSTERID = createField(DSL.name("lkmonsterid"), SQLDataType.BIGINT.nullable(false), this, "");

    private Lkdungeonlkmonsters(Name alias, Table<LkdungeonlkmonstersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lkdungeonlkmonsters(Name alias, Table<LkdungeonlkmonstersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.lkdungeonlkmonsters</code> table reference
     */
    public Lkdungeonlkmonsters(String alias) {
        this(DSL.name(alias), LKDUNGEONLKMONSTERS);
    }

    /**
     * Create an aliased <code>public.lkdungeonlkmonsters</code> table reference
     */
    public Lkdungeonlkmonsters(Name alias) {
        this(alias, LKDUNGEONLKMONSTERS);
    }

    /**
     * Create a <code>public.lkdungeonlkmonsters</code> table reference
     */
    public Lkdungeonlkmonsters() {
        this(DSL.name("lkdungeonlkmonsters"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<LkdungeonlkmonstersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.LKDUNGEONLKMONSTERS__LKDUNGEONLKMONSTERS_LKDUNGEONID_FKEY, Keys.LKDUNGEONLKMONSTERS__LKDUNGEONLKMONSTERS_LKMONSTERID_FKEY);
    }

    private transient LkdungeonsPath _lkdungeons;

    /**
     * Get the implicit join path to the <code>public.lkdungeons</code> table.
     */
    public LkdungeonsPath lkdungeons() {
        if (_lkdungeons == null)
            _lkdungeons = new LkdungeonsPath(this, Keys.LKDUNGEONLKMONSTERS__LKDUNGEONLKMONSTERS_LKDUNGEONID_FKEY, null);

        return _lkdungeons;
    }

    private transient LkmonstersPath _lkmonsters;

    /**
     * Get the implicit join path to the <code>public.lkmonsters</code> table.
     */
    public LkmonstersPath lkmonsters() {
        if (_lkmonsters == null)
            _lkmonsters = new LkmonstersPath(this, Keys.LKDUNGEONLKMONSTERS__LKDUNGEONLKMONSTERS_LKMONSTERID_FKEY, null);

        return _lkmonsters;
    }

    @Override
    public Lkdungeonlkmonsters as(String alias) {
        return new Lkdungeonlkmonsters(DSL.name(alias), this);
    }

    @Override
    public Lkdungeonlkmonsters as(Name alias) {
        return new Lkdungeonlkmonsters(alias, this);
    }

    @Override
    public Lkdungeonlkmonsters as(Table<?> alias) {
        return new Lkdungeonlkmonsters(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkdungeonlkmonsters rename(String name) {
        return new Lkdungeonlkmonsters(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkdungeonlkmonsters rename(Name name) {
        return new Lkdungeonlkmonsters(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkdungeonlkmonsters rename(Table<?> name) {
        return new Lkdungeonlkmonsters(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkmonsters where(Condition condition) {
        return new Lkdungeonlkmonsters(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkmonsters where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkmonsters where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkmonsters where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeonlkmonsters where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeonlkmonsters where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeonlkmonsters where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkdungeonlkmonsters where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkmonsters whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkdungeonlkmonsters whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
