/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.data_model.db_generated.Keys;
import space_habit_frontier.data_model.db_generated.Public;
import space_habit_frontier.data_model.db_generated.tables.records.LkmonstersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lkmonsters extends TableImpl<LkmonstersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.lkmonsters</code>
     */
    public static final Lkmonsters LKMONSTERS = new Lkmonsters();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LkmonstersRecord> getRecordType() {
        return LkmonstersRecord.class;
    }

    /**
     * The column <code>public.lkmonsters.id</code>.
     */
    public final TableField<LkmonstersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.lkmonsters.title</code>.
     */
    public final TableField<LkmonstersRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.lkmonsters.exposition</code>.
     */
    public final TableField<LkmonstersRecord, String> EXPOSITION = createField(DSL.name("exposition"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public final TableField<LkmonstersRecord, Object> LVLRANGE = createField(DSL.name("lvlrange"), DefaultDataType.getDefaultDataType("\"pg_catalog\".\"int4range\"").nullable(false), this, "");

    /**
     * The column <code>public.lkmonsters.xpmultiplier</code>.
     */
    public final TableField<LkmonstersRecord, Short> XPMULTIPLIER = createField(DSL.name("xpmultiplier"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.lkmonsters.imageuri</code>.
     */
    public final TableField<LkmonstersRecord, String> IMAGEURI = createField(DSL.name("imageuri"), SQLDataType.CLOB, this, "");

    private Lkmonsters(Name alias, Table<LkmonstersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lkmonsters(Name alias, Table<LkmonstersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.lkmonsters</code> table reference
     */
    public Lkmonsters(String alias) {
        this(DSL.name(alias), LKMONSTERS);
    }

    /**
     * Create an aliased <code>public.lkmonsters</code> table reference
     */
    public Lkmonsters(Name alias) {
        this(alias, LKMONSTERS);
    }

    /**
     * Create a <code>public.lkmonsters</code> table reference
     */
    public Lkmonsters() {
        this(DSL.name("lkmonsters"), null);
    }

    public <O extends Record> Lkmonsters(Table<O> path, ForeignKey<O, LkmonstersRecord> childPath, InverseForeignKey<O, LkmonstersRecord> parentPath) {
        super(path, childPath, parentPath, LKMONSTERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class LkmonstersPath extends Lkmonsters implements Path<LkmonstersRecord> {
        public <O extends Record> LkmonstersPath(Table<O> path, ForeignKey<O, LkmonstersRecord> childPath, InverseForeignKey<O, LkmonstersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private LkmonstersPath(Name alias, Table<LkmonstersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public LkmonstersPath as(String alias) {
            return new LkmonstersPath(DSL.name(alias), this);
        }

        @Override
        public LkmonstersPath as(Name alias) {
            return new LkmonstersPath(alias, this);
        }

        @Override
        public LkmonstersPath as(Table<?> alias) {
            return new LkmonstersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<LkmonstersRecord> getPrimaryKey() {
        return Keys.LKMONSTERS_PKEY;
    }

    @Override
    public Lkmonsters as(String alias) {
        return new Lkmonsters(DSL.name(alias), this);
    }

    @Override
    public Lkmonsters as(Name alias) {
        return new Lkmonsters(alias, this);
    }

    @Override
    public Lkmonsters as(Table<?> alias) {
        return new Lkmonsters(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkmonsters rename(String name) {
        return new Lkmonsters(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkmonsters rename(Name name) {
        return new Lkmonsters(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkmonsters rename(Table<?> name) {
        return new Lkmonsters(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkmonsters where(Condition condition) {
        return new Lkmonsters(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkmonsters where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkmonsters where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkmonsters where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkmonsters where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkmonsters where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkmonsters where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkmonsters where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkmonsters whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkmonsters whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
