/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.data_model.db_generated.Keys;
import space_habit_frontier.data_model.db_generated.Public;
import space_habit_frontier.data_model.db_generated.tables.records.LkusablesRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Lkusables extends TableImpl<LkusablesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.lkusables</code>
     */
    public static final Lkusables LKUSABLES = new Lkusables();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<LkusablesRecord> getRecordType() {
        return LkusablesRecord.class;
    }

    /**
     * The column <code>public.lkusables.id</code>.
     */
    public final TableField<LkusablesRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.lkusables.title</code>.
     */
    public final TableField<LkusablesRecord, String> TITLE = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.lkusables.exposition</code>.
     */
    public final TableField<LkusablesRecord, String> EXPOSITION = createField(DSL.name("exposition"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.lkusables.cost</code>.
     */
    public final TableField<LkusablesRecord, Integer> COST = createField(DSL.name("cost"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.lkusables.effecttypes</code>.
     */
    public final TableField<LkusablesRecord, Short[]> EFFECTTYPES = createField(DSL.name("effecttypes"), SQLDataType.SMALLINT.array(), this, "");

    /**
     * The column <code>public.lkusables.imageuri</code>.
     */
    public final TableField<LkusablesRecord, String> IMAGEURI = createField(DSL.name("imageuri"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.lkusables.hprestore</code>.
     */
    public final TableField<LkusablesRecord, Long> HPRESTORE = createField(DSL.name("hprestore"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.lkusables.xpbonus</code>.
     */
    public final TableField<LkusablesRecord, Long> XPBONUS = createField(DSL.name("xpbonus"), SQLDataType.BIGINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>public.lkusables.goldbonus</code>.
     */
    public final TableField<LkusablesRecord, Short> GOLDBONUS = createField(DSL.name("goldbonus"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.lkusables.damagebonus</code>.
     */
    public final TableField<LkusablesRecord, Short> DAMAGEBONUS = createField(DSL.name("damagebonus"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.lkusables.successrate</code>.
     */
    public final TableField<LkusablesRecord, Float> SUCCESSRATE = createField(DSL.name("successrate"), SQLDataType.REAL.nullable(false).defaultValue(DSL.field(DSL.raw("1"), SQLDataType.REAL)), this, "");

    /**
     * The column <code>public.lkusables.skips</code>.
     */
    public final TableField<LkusablesRecord, Short> SKIPS = createField(DSL.name("skips"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.lkusables.saves</code>.
     */
    public final TableField<LkusablesRecord, Short> SAVES = createField(DSL.name("saves"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    /**
     * The column <code>public.lkusables.duration</code>.
     */
    public final TableField<LkusablesRecord, Short> DURATION = createField(DSL.name("duration"), SQLDataType.SMALLINT.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.SMALLINT)), this, "");

    private Lkusables(Name alias, Table<LkusablesRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Lkusables(Name alias, Table<LkusablesRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.lkusables</code> table reference
     */
    public Lkusables(String alias) {
        this(DSL.name(alias), LKUSABLES);
    }

    /**
     * Create an aliased <code>public.lkusables</code> table reference
     */
    public Lkusables(Name alias) {
        this(alias, LKUSABLES);
    }

    /**
     * Create a <code>public.lkusables</code> table reference
     */
    public Lkusables() {
        this(DSL.name("lkusables"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<LkusablesRecord> getPrimaryKey() {
        return Keys.LKUSABLES_PKEY;
    }

    @Override
    public Lkusables as(String alias) {
        return new Lkusables(DSL.name(alias), this);
    }

    @Override
    public Lkusables as(Name alias) {
        return new Lkusables(alias, this);
    }

    @Override
    public Lkusables as(Table<?> alias) {
        return new Lkusables(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkusables rename(String name) {
        return new Lkusables(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkusables rename(Name name) {
        return new Lkusables(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Lkusables rename(Table<?> name) {
        return new Lkusables(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkusables where(Condition condition) {
        return new Lkusables(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkusables where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkusables where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkusables where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkusables where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkusables where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkusables where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Lkusables where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkusables whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Lkusables whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
