/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.data_model.db_generated.Keys;
import space_habit_frontier.data_model.db_generated.Public;
import space_habit_frontier.data_model.db_generated.tables.Lkitems.LkitemsPath;
import space_habit_frontier.data_model.db_generated.tables.Lkmonsters.LkmonstersPath;
import space_habit_frontier.data_model.db_generated.tables.records.MonsteritemdropsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Monsteritemdrops extends TableImpl<MonsteritemdropsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.monsteritemdrops</code>
     */
    public static final Monsteritemdrops MONSTERITEMDROPS = new Monsteritemdrops();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MonsteritemdropsRecord> getRecordType() {
        return MonsteritemdropsRecord.class;
    }

    /**
     * The column <code>public.monsteritemdrops.lkmonsterid</code>.
     */
    public final TableField<MonsteritemdropsRecord, Long> LKMONSTERID = createField(DSL.name("lkmonsterid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.monsteritemdrops.lkitemid</code>.
     */
    public final TableField<MonsteritemdropsRecord, Long> LKITEMID = createField(DSL.name("lkitemid"), SQLDataType.BIGINT.nullable(false), this, "");

    private Monsteritemdrops(Name alias, Table<MonsteritemdropsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Monsteritemdrops(Name alias, Table<MonsteritemdropsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.monsteritemdrops</code> table reference
     */
    public Monsteritemdrops(String alias) {
        this(DSL.name(alias), MONSTERITEMDROPS);
    }

    /**
     * Create an aliased <code>public.monsteritemdrops</code> table reference
     */
    public Monsteritemdrops(Name alias) {
        this(alias, MONSTERITEMDROPS);
    }

    /**
     * Create a <code>public.monsteritemdrops</code> table reference
     */
    public Monsteritemdrops() {
        this(DSL.name("monsteritemdrops"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<ForeignKey<MonsteritemdropsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MONSTERITEMDROPS__MONSTERITEMDROPS_LKMONSTERID_FKEY, Keys.MONSTERITEMDROPS__MONSTERITEMDROPS_LKITEMID_FKEY);
    }

    private transient LkmonstersPath _lkmonsters;

    /**
     * Get the implicit join path to the <code>public.lkmonsters</code> table.
     */
    public LkmonstersPath lkmonsters() {
        if (_lkmonsters == null)
            _lkmonsters = new LkmonstersPath(this, Keys.MONSTERITEMDROPS__MONSTERITEMDROPS_LKMONSTERID_FKEY, null);

        return _lkmonsters;
    }

    private transient LkitemsPath _lkitems;

    /**
     * Get the implicit join path to the <code>public.lkitems</code> table.
     */
    public LkitemsPath lkitems() {
        if (_lkitems == null)
            _lkitems = new LkitemsPath(this, Keys.MONSTERITEMDROPS__MONSTERITEMDROPS_LKITEMID_FKEY, null);

        return _lkitems;
    }

    @Override
    public Monsteritemdrops as(String alias) {
        return new Monsteritemdrops(DSL.name(alias), this);
    }

    @Override
    public Monsteritemdrops as(Name alias) {
        return new Monsteritemdrops(alias, this);
    }

    @Override
    public Monsteritemdrops as(Table<?> alias) {
        return new Monsteritemdrops(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Monsteritemdrops rename(String name) {
        return new Monsteritemdrops(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Monsteritemdrops rename(Name name) {
        return new Monsteritemdrops(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Monsteritemdrops rename(Table<?> name) {
        return new Monsteritemdrops(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Monsteritemdrops where(Condition condition) {
        return new Monsteritemdrops(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Monsteritemdrops where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Monsteritemdrops where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Monsteritemdrops where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Monsteritemdrops where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Monsteritemdrops where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Monsteritemdrops where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Monsteritemdrops where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Monsteritemdrops whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Monsteritemdrops whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
