/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.data_model.db_generated.Keys;
import space_habit_frontier.data_model.db_generated.Public;
import space_habit_frontier.data_model.db_generated.tables.Todos.TodosPath;
import space_habit_frontier.data_model.db_generated.tables.Users.UsersPath;
import space_habit_frontier.data_model.db_generated.tables.records.TodoeventsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Todoevents extends TableImpl<TodoeventsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.todoevents</code>
     */
    public static final Todoevents TODOEVENTS = new Todoevents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TodoeventsRecord> getRecordType() {
        return TodoeventsRecord.class;
    }

    /**
     * The column <code>public.todoevents.id</code>.
     */
    public final TableField<TodoeventsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.todoevents.damage</code>.
     */
    public final TableField<TodoeventsRecord, Integer> DAMAGE = createField(DSL.name("damage"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.todoevents.creationtimestamp</code>.
     */
    public final TableField<TodoeventsRecord, OffsetDateTime> CREATIONTIMESTAMP = createField(DSL.name("creationtimestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.todoevents.todoid</code>.
     */
    public final TableField<TodoeventsRecord, UUID> TODOID = createField(DSL.name("todoid"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.todoevents.userid</code>.
     */
    public final TableField<TodoeventsRecord, UUID> USERID = createField(DSL.name("userid"), SQLDataType.UUID.nullable(false), this, "");

    private Todoevents(Name alias, Table<TodoeventsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Todoevents(Name alias, Table<TodoeventsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.todoevents</code> table reference
     */
    public Todoevents(String alias) {
        this(DSL.name(alias), TODOEVENTS);
    }

    /**
     * Create an aliased <code>public.todoevents</code> table reference
     */
    public Todoevents(Name alias) {
        this(alias, TODOEVENTS);
    }

    /**
     * Create a <code>public.todoevents</code> table reference
     */
    public Todoevents() {
        this(DSL.name("todoevents"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TodoeventsRecord> getPrimaryKey() {
        return Keys.TODOEVENTS_PKEY;
    }

    @Override
    public List<ForeignKey<TodoeventsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TODOEVENTS__TODOEVENTS_TODOID_FKEY, Keys.TODOEVENTS__TODOEVENTS_USERID_FKEY);
    }

    private transient TodosPath _todos;

    /**
     * Get the implicit join path to the <code>public.todos</code> table.
     */
    public TodosPath todos() {
        if (_todos == null)
            _todos = new TodosPath(this, Keys.TODOEVENTS__TODOEVENTS_TODOID_FKEY, null);

        return _todos;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.TODOEVENTS__TODOEVENTS_USERID_FKEY, null);

        return _users;
    }

    @Override
    public Todoevents as(String alias) {
        return new Todoevents(DSL.name(alias), this);
    }

    @Override
    public Todoevents as(Name alias) {
        return new Todoevents(alias, this);
    }

    @Override
    public Todoevents as(Table<?> alias) {
        return new Todoevents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Todoevents rename(String name) {
        return new Todoevents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todoevents rename(Name name) {
        return new Todoevents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todoevents rename(Table<?> name) {
        return new Todoevents(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todoevents where(Condition condition) {
        return new Todoevents(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todoevents where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todoevents where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todoevents where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todoevents where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todoevents where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todoevents where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Todoevents where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todoevents whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Todoevents whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
