/*
 * This file is generated by jOOQ.
 */
package space_habit_frontier.data_model.db_generated.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import space_habit_frontier.data_model.db_generated.Keys;
import space_habit_frontier.data_model.db_generated.Public;
import space_habit_frontier.data_model.db_generated.tables.Users.UsersPath;
import space_habit_frontier.data_model.db_generated.tables.Visitors.VisitorsPath;
import space_habit_frontier.data_model.db_generated.tables.records.UsersessionsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Usersessions extends TableImpl<UsersessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.usersessions</code>
     */
    public static final Usersessions USERSESSIONS = new Usersessions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsersessionsRecord> getRecordType() {
        return UsersessionsRecord.class;
    }

    /**
     * The column <code>public.usersessions.id</code>.
     */
    public final TableField<UsersessionsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.usersessions.username</code>.
     */
    public final TableField<UsersessionsRecord, String> USERNAME = createField(DSL.name("username"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.usersessions.creationtimestamp</code>.
     */
    public final TableField<UsersessionsRecord, OffsetDateTime> CREATIONTIMESTAMP = createField(DSL.name("creationtimestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.usersessions.expirationtimestamp</code>.
     */
    public final TableField<UsersessionsRecord, OffsetDateTime> EXPIRATIONTIMESTAMP = createField(DSL.name("expirationtimestamp"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "");

    /**
     * The column <code>public.usersessions.userid</code>.
     */
    public final TableField<UsersessionsRecord, UUID> USERID = createField(DSL.name("userid"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.usersessions.visitorid</code>.
     */
    public final TableField<UsersessionsRecord, Long> VISITORID = createField(DSL.name("visitorid"), SQLDataType.BIGINT.nullable(false), this, "");

    private Usersessions(Name alias, Table<UsersessionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Usersessions(Name alias, Table<UsersessionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.usersessions</code> table reference
     */
    public Usersessions(String alias) {
        this(DSL.name(alias), USERSESSIONS);
    }

    /**
     * Create an aliased <code>public.usersessions</code> table reference
     */
    public Usersessions(Name alias) {
        this(alias, USERSESSIONS);
    }

    /**
     * Create a <code>public.usersessions</code> table reference
     */
    public Usersessions() {
        this(DSL.name("usersessions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UsersessionsRecord> getPrimaryKey() {
        return Keys.USERSESSIONS_PKEY;
    }

    @Override
    public List<ForeignKey<UsersessionsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USERSESSIONS__USERSESSIONS_USERID_FKEY, Keys.USERSESSIONS__USERSESSIONS_VISITORID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.USERSESSIONS__USERSESSIONS_USERID_FKEY, null);

        return _users;
    }

    private transient VisitorsPath _visitors;

    /**
     * Get the implicit join path to the <code>public.visitors</code> table.
     */
    public VisitorsPath visitors() {
        if (_visitors == null)
            _visitors = new VisitorsPath(this, Keys.USERSESSIONS__USERSESSIONS_VISITORID_FKEY, null);

        return _visitors;
    }

    @Override
    public Usersessions as(String alias) {
        return new Usersessions(DSL.name(alias), this);
    }

    @Override
    public Usersessions as(Name alias) {
        return new Usersessions(alias, this);
    }

    @Override
    public Usersessions as(Table<?> alias) {
        return new Usersessions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Usersessions rename(String name) {
        return new Usersessions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Usersessions rename(Name name) {
        return new Usersessions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Usersessions rename(Table<?> name) {
        return new Usersessions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usersessions where(Condition condition) {
        return new Usersessions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usersessions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usersessions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usersessions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Usersessions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Usersessions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Usersessions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Usersessions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usersessions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Usersessions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
